// Listes de mots par niveau — français uniquement.
// Sources : échelle Dubois-Buyse (vocabulaire par niveau) + Lexique 3.83 (fréquences), triées par simplicité orthographique.
// Modifier librement : une entrée = un mot.
const MOTS = {
  "CP": [
    "achat", "acier", "acte", "actif", "actuel", "adieu", "adroit", "afin", "agent", "agile", "agir", "aide",
    "aigle", "aile", "air", "aise", "alors", "amande", "amateur", "ami", "amour", "ange", "animal", "année",
    "après", "ardeur", "ardoise", "arme", "armer", "armoire", "armée", "art", "article", "artiste", "aube",
    "aussi", "autel", "autour", "autre", "avant", "avec", "avenir", "avertir", "aveugle", "avion", "avis",
    "avoir", "avril", "bain", "bal", "balcon", "baleine", "balle", "banc", "bande", "barbe", "barque", "bas",
    "bassin", "bazar", "beau", "bec", "belge", "bien", "bijou", "biscuit", "bise", "bleu", "bloc", "blond",
    "blouse", "blé", "boeuf", "boire", "bois", "bon", "bond", "bondir", "bonheur", "bonjour", "bonne",
    "bonté", "bord", "bordure", "borne", "botte", "boucle", "boue", "boule", "bourse", "bout", "bouton",
    "bras", "brave", "bravo", "bref", "brin", "brique", "brise", "bruit", "brume", "brun", "brusque", "brut",
    "brutal", "bureau", "but", "bâtir", "bâton", "bébé", "bénir", "bêche", "bête", "cabine", "cadet", "cadre",
    "café", "cage", "cahier", "calcul", "calme", "camion", "camp", "canal", "canard", "canif", "canon", "car",
    "caramel", "carnet", "carte", "carton", "cas", "cause", "cave", "caverne", "ceci", "cela", "cent", "cerf",
    "chacun", "chair", "chaleur", "charbon", "charge", "charité", "charme", "chat", "chef", "chemin",
    "chemise", "cher", "cheval", "chez", "chien", "choc", "chose", "chute", "chéri", "chêne", "ciel", "cinq",
    "cirque", "citron", "cité", "clair", "clarté", "classe", "clef", "cloche", "clou", "clé", "cochon",
    "coeur", "coin", "combien", "comme", "commun", "commune", "congé", "conte", "contenu", "copain", "coq",
    "corbeau", "corde", "corne", "costume", "coton", "cou", "coucou", "coude", "coudre", "couleur", "coup",
    "coupe", "couper", "cour", "courage", "cours", "course", "court", "cousin", "cousine", "coutume",
    "couvrir", "cri", "crier", "crime", "crise", "croire", "cuir", "cuire", "cuisine", "cuivre", "culture",
    "curé", "côte", "côté", "dame", "dans", "danse", "date", "degré", "demain", "demande", "demi", "dent",
    "depuis", "dernier", "dessin", "deuil", "devant", "devenir", "devoir", "diable", "dictée", "dire",
    "divin", "docteur", "doigt", "donc", "dont", "dormir", "dos", "double", "douleur", "doute", "douze",
    "dragon", "drap", "droit", "droite", "drôle", "duc", "dur", "durer", "durée", "duvet", "dès", "début",
    "désir", "dîner", "eau", "encore", "enfin", "engager", "ensuite", "entier", "espoir", "face", "facteur",
    "faim", "faire", "fait", "fantôme", "farce", "farine", "fatal", "fatigue", "faute", "fauve", "faveur",
    "femme", "fenêtre", "fer", "ferme", "fermier", "feu", "fidèle", "fier", "figure", "fil", "file", "filet",
    "fils", "fin", "finir", "fièvre", "fleur", "fleuve", "flot", "fléau", "foi", "foie", "foin", "foire",
    "fois", "fond", "force", "forge", "forme", "fort", "fortune", "forêt", "fou", "foudre", "fouet", "foule",
    "four", "fournir", "frais", "franc", "froid", "fromage", "front", "fruit", "frère", "frémir", "fuir",
    "fuite", "fumer", "fumée", "fusil", "fusée", "futur", "fée", "fête", "fêter", "gamin", "gant", "garde",
    "gardien", "gare", "garnir", "garçon", "gaz", "gazon", "geler", "gelée", "genre", "gens", "gerbe",
    "geste", "gibier", "girafe", "givre", "glace", "gloire", "gomme", "gorge", "goût", "grain", "grand",
    "grandir", "gras", "grave", "gravir", "grenier", "gris", "grive", "groupe", "grue", "grâce", "grès",
    "guitare", "gémir", "haricot", "herbe", "hibou", "hier", "hiver", "ici", "idée", "image", "inconnu",
    "insecte", "ivre", "jadis", "jambe", "janvier", "jardin", "jaune", "jeter", "jeu", "jeudi", "jeune",
    "joie", "joli", "joue", "jouer", "jouet", "joueur", "jouir", "joujou", "jour", "journal", "journée",
    "juge", "juger", "juin", "jurer", "jusque", "juste", "labeur", "lac", "laid", "laine", "lait", "lampe",
    "lapin", "large", "larme", "las", "laver", "lecture", "lent", "leur", "lever", "leçon", "liberté",
    "libre", "lien", "lier", "lieu", "ligue", "lilas", "limite", "lin", "linge", "lion", "liquide", "lire",
    "lis", "liste", "lit", "livre", "livrer", "lièvre", "local", "loger", "loi", "loin", "loisir", "long",
    "lors", "lot", "louer", "loup", "lueur", "lui", "luire", "lumière", "lundi", "lune", "lunette", "lutin",
    "lutte", "lèvre", "léger", "légume", "machine", "madame", "magique", "mai", "main", "mais", "maison",
    "mal", "malade", "maladie", "malin", "maman", "mamie", "manger", "manuel", "marche", "marcher", "mardi",
    "mare", "mari", "mariage", "marin", "marque", "marquer", "mars", "matin", "matinal", "matinée", "matière",
    "mauve", "maître", "mener", "menteur", "menu", "mer", "merci", "merle", "messe", "meuble", "midi", "miel",
    "mien", "miette", "mine", "mineur", "minuit", "minute", "miracle", "mirer", "miroir", "mode", "moderne",
    "moine", "moineau", "mois", "moitié", "moment", "monde", "mont", "morne", "mort", "mortel", "moteur",
    "motif", "mou", "moudre", "moulin", "mouton", "mouvoir", "muet", "munir", "mur", "murmure", "musique",
    "musée", "mère", "mètre", "mélange", "mémoire", "métal", "métier", "métro", "même", "nager", "nappe",
    "natal", "nature", "navet", "navire", "neige", "net", "neuf", "nez", "niche", "nid", "noble", "nom",
    "non", "nord", "normal", "note", "nuage", "nuit", "nul", "objet", "obliger", "octobre", "odeur", "oeuf",
    "oie", "oiseau", "onde", "onze", "orage", "orange", "orner", "osier", "oui", "ours", "outre", "ouvrage",
    "ouvrier", "page", "pain", "paire", "panier", "papa", "papi", "papier", "par", "parc", "pardon", "parent",
    "parfait", "parole", "part", "parti", "partie", "partir", "partout", "pas", "patin", "patrie", "patron",
    "patte", "pauvre", "pavé", "peau", "perche", "perle", "perte", "peser", "petit", "peu", "peuple", "peur",
    "piano", "pic", "pie", "pied", "pin", "pipe", "pirate", "piscine", "piste", "pitié", "pièce", "piété",
    "place", "placer", "plage", "plaisir", "plan", "plante", "plaque", "plat", "pleur", "plier", "plonger",
    "pluie", "plumage", "plume", "plumier", "plus", "poche", "poil", "point", "pointe", "poire", "poisson",
    "poli", "pomme", "pompe", "pont", "porc", "port", "porte", "porter", "porteur", "poser", "postal",
    "poste", "pot", "poudre", "poule", "poulet", "poupée", "pour", "pouvoir", "poésie", "prairie", "premier",
    "presque", "preuve", "prier", "prime", "prince", "prise", "prison", "prière", "proche", "produit",
    "proie", "propre", "près", "préau", "prévoir", "prêt", "prêtre", "puis", "puisque", "punir", "pupitre",
    "pur", "pâle", "pâlir", "pâte", "pâtre", "père", "péché", "pénible", "pépite", "péril", "périr", "pétrir",
    "quatre", "quel", "quoi", "race", "racine", "radis", "rage", "raison", "ramage", "rame", "rang", "rare",
    "raser", "rat", "ravin", "ravir", "recette", "regard", "reine", "relatif", "relire", "remise", "renard",
    "repas", "repos", "reprise", "requin", "reste", "retenir", "retour", "revenir", "revivre", "revoir",
    "revue", "riche", "rider", "rien", "rire", "risque", "rive", "rivière", "riz", "robe", "robuste",
    "rocher", "roi", "rond", "ronde", "rose", "rosée", "roue", "rouge", "route", "ruban", "ruche", "rude",
    "rue", "ruelle", "ruine", "rusé", "règle", "récolte", "réduire", "régime", "réponse", "réunion", "réunir",
    "rêve", "rôle", "sable", "sablé", "sabot", "sabre", "sac", "sacoche", "sacré", "sage", "sain", "saison",
    "salade", "sale", "salir", "salle", "salon", "salut", "samedi", "sang", "sans", "santé", "sapin", "satin",
    "saut", "sauvage", "savoir", "savon", "seau", "sec", "sel", "selon", "semaine", "semer", "sept", "servir",
    "seul", "sien", "singe", "sinon", "sitôt", "siècle", "siège", "sobre", "soeur", "soie", "soif", "soin",
    "soir", "sol", "soldat", "soleil", "solide", "son", "sort", "sorte", "sortie", "sortir", "sot", "sou",
    "soupe", "sous", "statue", "suave", "subir", "sucre", "sud", "sueur", "suite", "suivre", "sujet",
    "superbe", "sur", "surgir", "surtout", "sève", "série", "sévir", "table", "tableau", "tablier", "tache",
    "tant", "tante", "tapis", "tard", "tarte", "tartine", "tas", "tasse", "tel", "tenir", "tenue", "terme",
    "terre", "tige", "tigre", "timide", "tirer", "tiroir", "titre", "tiède", "toile", "toit", "tomate",
    "tombe", "tomber", "ton", "tortue", "tour", "tourner", "tous", "tout", "trace", "train", "tram", "triste",
    "trois", "trop", "trou", "trouble", "troupe", "très", "trésor", "tuer", "tuile", "tulipe", "tête", "tôt",
    "union", "unique", "unir", "usage", "usine", "utile", "vache", "valet", "valeur", "valise", "valoir",
    "vapeur", "vase", "vaste", "veau", "vendeur", "venir", "vent", "vente", "verdure", "verger", "vernir",
    "vert", "vertu", "veuf", "vice", "victime", "vide", "vider", "vie", "vierge", "vif", "visage", "viser",
    "visible", "visite", "vite", "vitesse", "vitre", "vitrine", "vivre", "voici", "voie", "voile", "voir",
    "voisin", "voiture", "vol", "voler", "volet", "voleur", "volume", "volée", "vue", "vélo", "vôtre", "word",
    "zèbre", "zèle", "âge", "âme", "âne", "écharpe", "éclat", "écluse", "école", "écolier", "écrire", "écrit",
    "écurie", "église", "élève", "énorme", "épine", "épreuve", "épée", "étable", "établir", "étage",
    "étalage", "état", "éternel", "étoile", "étrange", "étude", "été", "être", "île"
  ],
  "CE1": [
    "abeille", "aborder", "aboutir", "abricot", "abriter", "absent", "absolu", "abuser", "accord", "acheter",
    "achever", "action", "activer", "addition", "admirer", "adopter", "adorer", "adoucir", "affaiblir",
    "agréable", "aider", "aimable", "aimer", "ajouter", "alerte", "aliment", "aller", "allure", "allée",
    "amener", "amical", "amusant", "amuser", "ancien", "angle", "animer", "appel", "apôtre", "arbitre",
    "arbre", "arbuste", "ardent", "argent", "arrêt", "aspirer", "assidu", "astre", "atelier", "auberge",
    "aucun", "aumône", "auprès", "auquel", "aurore", "autant", "auteur", "autobus", "autrui", "avaler",
    "avance", "avancer", "avenue", "averse", "aviateur", "aviser", "avoine", "avouer", "azuré", "aérer",
    "bagage", "ballon", "banane", "bandit", "banque", "barquette", "barre", "basse", "bataille", "bavarder",
    "beauté", "berceau", "berger", "besogne", "besoin", "bientôt", "bille", "billet", "blancheur", "blanchir",
    "bleuet", "bluet", "bonbon", "bonnet", "bonsoir", "border", "bosquet", "bossu", "bouche", "boucler",
    "bouder", "bouger", "bougie", "boulanger", "boulangerie", "bouquet", "boutique", "bracelet", "branche",
    "brebis", "brioche", "briser", "brochure", "broder", "brouter", "butiner", "bétail", "cabane", "cacher",
    "cadeau", "cadran", "calculer", "calice", "calmer", "camarade", "campagne", "canne", "capable",
    "capitaine", "capital", "caprice", "carabine", "carré", "cartable", "casser", "casserole", "causer",
    "cendre", "centime", "centre", "cercle", "cerise", "cerisier", "certain", "cesser", "chagrin", "chaise",
    "chambre", "champ", "champignon", "chance", "chanson", "chant", "chanteur", "chantre", "chapeau",
    "chapelle", "chapitre", "chaque", "charger", "charitable", "charmer", "chasse", "chasseur", "chaud",
    "chaudement", "chaume", "chaussette", "cheminée", "chercher", "chevalier", "chevelure", "chocolat",
    "choisir", "chouette", "chèvre", "chérir", "cinéma", "circuler", "citrouille", "clairon", "claquer",
    "client", "climat", "clocher", "clochette", "clouer", "clément", "colonel", "colonial", "colorer",
    "colère", "combat", "comble", "compagne", "compagnie", "compagnon", "comparer", "compliment", "conduire",
    "conduite", "confier", "confiture", "confondre", "confrère", "conseil", "contenir", "contre",
    "contribuer", "convenable", "convenir", "copier", "coquet", "corbeille", "cordial", "corniche", "corps",
    "cortège", "couche", "couler", "couloir", "coupable", "courber", "coureur", "courgette", "courir",
    "couture", "couver", "couvert", "couverture", "crainte", "craquer", "creuser", "crever", "cristal",
    "crocodile", "croix", "créateur", "créature", "cultiver", "céleste", "cœur", "danger", "danser",
    "dauphin", "debout", "dedans", "dehors", "demeure", "dessus", "destination", "destiner", "destinée",
    "dette", "deux", "deviner", "digne", "dimanche", "diminuer", "directement", "directeur", "diriger",
    "discuter", "disposer", "disputer", "divers", "diviser", "division", "dix", "dizaine", "docile",
    "domestique", "domicile", "dominer", "donner", "doubler", "douceur", "douloureux", "douter", "doux",
    "drapeau", "dromadaire", "duquel", "durant", "débiter", "déborder", "décembre", "décider", "déclarer",
    "décorer", "découverte", "décrire", "défaire", "défaut", "défense", "dégager", "délicat", "délice",
    "délivrer", "démarche", "démolir", "dénudé", "départ", "dépenser", "déplacer", "déplaire", "déposer",
    "dérober", "désagréable", "désirer", "désoler", "détail", "détester", "détour", "détruire", "dévorer",
    "dévouer", "effet", "effort", "emplir", "encre", "encrier", "endormir", "enfant", "enfouir", "enlever",
    "ennemi", "entre", "entreprendre", "entrer", "entretenir", "entrevoir", "entrée", "envie", "envier",
    "environ", "erreur", "escalier", "escargot", "esclave", "espace", "esprit", "espérer", "estime",
    "estimer", "estomac", "estrade", "fabrique", "facile", "faible", "falloir", "famille", "fauvette",
    "favorable", "façon", "fendre", "fermer", "ferrer", "ferveur", "feuille", "figurer", "fille", "flacon",
    "flamand", "flamme", "flaque", "fleurette", "flocon", "flèche", "fondre", "fontaine", "forcer", "forger",
    "forgeron", "former", "formidable", "fortement", "fossé", "fougère", "fourchette", "fourmi", "fragile",
    "fraise", "franchir", "froment", "fruitier", "fureur", "féroce", "février", "gagner", "galerie", "garage",
    "garantir", "garder", "gauche", "gendarme", "gentil", "germer", "giroflée", "gosse", "graine",
    "grammaire", "grandeur", "grange", "grappe", "graver", "gravure", "grenouille", "griffe", "grimper",
    "grippe", "gronder", "grossir", "grotte", "guide", "guérir", "gâteau", "géant", "général", "habit",
    "hache", "haie", "haine", "haut", "heure", "hippopotame", "homme", "honte", "huile", "huit", "humeur",
    "humide", "hurler", "hâte", "hélas", "hérisson", "hêtre", "idéal", "imiter", "indigne", "industrie",
    "inerte", "infini", "infirme", "ingrat", "injure", "inscrire", "inspecteur", "instituteur", "instrument",
    "intervenir", "intime", "inutile", "invisible", "inviter", "isoler", "ivoire", "jamais", "jambon",
    "jardinier", "jaunir", "joindre", "journalier", "juillet", "justement", "justice", "kangourou", "képi",
    "laboureur", "laitier", "langage", "langue", "lanterne", "lenteur", "lequel", "lettre", "libérer",
    "ligne", "limiter", "limpide", "lisière", "lisse", "litière", "locomotive", "longer", "lorsque",
    "louange", "lourd", "lugubre", "luisant", "lunettes", "lutter", "lys", "lécher", "mademoiselle",
    "magasin", "magicien", "magnifique", "maigre", "majesté", "malgré", "manche", "manier", "manière",
    "manque", "marbre", "marché", "marier", "marquis", "marteau", "masse", "massif", "maternel", "matériel",
    "membre", "mendier", "mensuel", "mentir", "menton", "mercredi", "merveille", "mesure", "mesurer", "meule",
    "meunier", "mignon", "migrateur", "milieu", "mince", "ministre", "misère", "misérable", "mobile",
    "modeste", "modestie", "modèle", "moindre", "monotone", "monstre", "montagne", "monter", "montre",
    "moquer", "moqueur", "morale", "morceau", "mordre", "mouche", "mouchoir", "mouette", "mourir",
    "moustache", "mouvement", "multiple", "multitude", "muraille", "murmurer", "muscle", "museau", "musicien",
    "médecin", "méditer", "mélodie", "ménage", "ménager", "ménagerie", "ménagère", "mériter", "nation",
    "naturel", "naturellement", "neiger", "niveau", "nombre", "nommer", "notaire", "nuisible", "numéro",
    "négliger", "observer", "obtenir", "obéir", "océan", "odorant", "oeuvre", "office", "offre", "ombrage",
    "ombre", "oncle", "onduler", "opérer", "oranger", "ordre", "oreille", "orgue", "ouate", "outil",
    "ouverture", "ouvrir", "paille", "paisible", "palais", "panache", "panthère", "paquet", "paradis",
    "parages", "parcourir", "parfois", "parfum", "parfumer", "parler", "parquet", "partager", "parure",
    "parvenir", "passer", "passé", "pays", "peine", "pelage", "pelouse", "pendant", "pendre", "pendule",
    "pension", "pensée", "percher", "perdre", "personne", "peupler", "peuplier", "phoque", "pigeon",
    "pingouin", "pinson", "piquer", "plaie", "plaine", "plainte", "plaintif", "plaire", "planche", "planer",
    "planter", "planète", "plateau", "plein", "pleurer", "pleuvoir", "plomb", "plutôt", "pointu", "poireau",
    "poirier", "poitrine", "poivron", "police", "politesse", "politique", "pompier", "pondre", "portière",
    "portée", "potager", "poteau", "potiron", "poumon", "pourpre", "pourquoi", "pourvoir", "poutre",
    "pratique", "pratiquer", "prendre", "primaire", "principe", "priver", "problème", "procurer", "procureur",
    "production", "produire", "profit", "profiter", "profond", "profondeur", "promenade", "promener",
    "propos", "proposer", "proposition", "proprement", "propreté", "protecteur", "protéger", "prouver",
    "provenir", "proverbe", "prudence", "prudent", "préparer", "présence", "présent", "prévenir", "prêcher",
    "purifier", "pâture", "pénétrer", "période", "pétale", "pêche", "pêcher", "pêcheur", "qualité", "quand",
    "quart", "quatorze", "quelque", "quinze", "quoique", "raide", "raisin", "ralentir", "rameau", "ramener",
    "ranimer", "rapide", "rarement", "ravage", "recevoir", "recourir", "recueil", "reculer", "redevenir",
    "redire", "redoutable", "refaire", "refermer", "reflet", "refrain", "refuge", "refuser", "regarder",
    "regret", "rejeter", "relever", "religion", "remarque", "remplir", "remuer", "remède", "rencontre",
    "rendre", "rentrer", "repentir", "replier", "reporter", "reposer", "reprendre", "reproche", "respect",
    "respiration", "respirer", "rester", "retard", "retentir", "retirer", "retraite", "reverdir", "revêtir",
    "riant", "rideau", "rigole", "risquer", "rompre", "ronce", "ronger", "roseau", "rosier", "rougir",
    "rouler", "ruiner", "rustique", "règne", "réclamer", "récolter", "rédaction", "réformer", "réfugier",
    "régaler", "région", "régler", "régulier", "réjouir", "réparer", "répartir", "répondre", "répéter",
    "réserve", "réserver", "résister", "résoudre", "résultat", "rétablir", "réveil", "saint", "saisir",
    "salaire", "saluer", "salutation", "sanglier", "saule", "sauter", "sauver", "savant", "scolaire",
    "second", "seconde", "secouer", "secourir", "secret", "seize", "sensible", "sentier", "sentir", "sergent",
    "serrer", "servante", "serviable", "service", "serviteur", "seuil", "signal", "signature", "signe",
    "signer", "silence", "simple", "sincère", "singulier", "sirène", "situer", "société", "soirée",
    "solitude", "sombre", "somme", "sommet", "songer", "sonner", "sonore", "soulagement", "soulier", "souper",
    "soupir", "souple", "source", "sourd", "sourire", "souris", "soutenir", "souvenir", "spectateur",
    "station", "stylo", "sublime", "succès", "suivant", "suprême", "surface", "surprise", "survenir",
    "séjour", "séparer", "sœur", "taille", "taire", "talent", "tambour", "tantôt", "tapage", "tarder",
    "teinte", "temps", "tempête", "tendre", "tente", "terminer", "timbre", "tinter", "tirelire", "tombeau",
    "tordre", "toucher", "tournée", "tracteur", "tramway", "tranche", "travail", "traverser", "treize",
    "trente", "tribunal", "tricolore", "tricot", "tricoter", "tristement", "tromper", "tronc", "troubler",
    "trouer", "trouver", "tâche", "témoin", "urgence", "urgent", "utilité", "vague", "vallée", "vanille",
    "varier", "veine", "velouté", "vendre", "vendredi", "venger", "ventre", "verre", "verser", "veston",
    "viande", "vicaire", "victoire", "vieux", "vigne", "vigueur", "vilain", "villa", "village", "ville",
    "vingt", "violence", "violent", "violet", "violette", "visiter", "visiteur", "vivant", "vivement",
    "voiler", "voisinage", "volcan", "volonté", "voltiger", "vouloir", "voyageur", "végétal", "vénérer",
    "vérifier", "véritable", "vérité", "éblouir", "écarter", "échapper", "échelle", "éclair", "éclater",
    "éclore", "écouler", "écouter", "écriture", "édifier", "égarer", "élancer", "élargir", "élever",
    "élégant", "émouvoir", "énergie", "épais", "épanouir", "épargne", "épaule", "épauler", "époque",
    "épouser", "épuiser", "équipe", "étagère", "étaler", "étang", "étendue", "étirer", "étoffe", "étourdi",
    "étroit", "étudier", "éventuel", "éviter"
  ],
  "CE2": [
    "abattre", "abbé", "abondance", "abondant", "abord", "aboyer", "abri", "absence", "abîme", "abîmer",
    "accident", "acclamer", "accorder", "accuser", "acharner", "acheteur", "acide", "activité", "admirable",
    "adresse", "adresser", "affaire", "affection", "affiche", "agacer", "agitation", "agiter", "agréer",
    "agrément", "aigu", "aiguille", "ainsi", "aire", "aisé", "alcool", "allonger", "allumer", "allumette",
    "alouette", "ambiance", "amende", "amer", "amitié", "amnésie", "ample", "amusement", "anglais",
    "animation", "annonce", "annuel", "anxiété", "août", "apaiser", "apparence", "apporter", "approche",
    "approcher", "appui", "aquarium", "araignée", "arracher", "arriver", "arrivée", "arrière", "arroser",
    "assez", "assister", "assurance", "assurer", "atome", "attaque", "attaquer", "attendre", "attentif",
    "attention", "attirer", "attribuer", "aubergine", "aubépine", "aussitôt", "automne", "autoriser",
    "autorité", "autrefois", "autrement", "avantage", "aventure", "azote", "azur", "aîné", "baguette",
    "baisser", "balancer", "bambin", "banquier", "baptême", "barrière", "bateau", "battre", "beaucoup",
    "bercer", "betterave", "beurre", "bibelot", "bienfait", "bienvenue", "blessure", "blottir", "boisson",
    "boiteux", "bonhomme", "boucher", "boueux", "bouillon", "bourgeon", "boussole", "bouteille", "boîte",
    "brigand", "brindille", "brouillon", "broyer", "brumeux", "bruyant", "brèche", "brûlant", "brûler",
    "buis", "buisson", "bâillon", "bâtiment", "béret", "caisse", "calvaire", "canot", "cantique", "caractère",
    "carbone", "carillon", "carotte", "carreau", "carrière", "casquette", "celle-ci", "celui-ci", "centaine",
    "central", "cercueil", "cesse", "ceux", "chameau", "changer", "chanter", "chapelet", "chariot",
    "charmant", "chasser", "chauffage", "chauffer", "chauffeur", "chaumière", "chausser", "chaussure",
    "chaussée", "chaux", "chaîne", "chevet", "cheveu", "chevreuil", "chiffon", "chiffre", "choeur", "choix",
    "chou", "châtaigne", "château", "cime", "cimetière", "cinquante", "cirer", "citer", "citoyen", "civil",
    "clairière", "classique", "clos", "clown", "coffre", "coffret", "coiffer", "coiffure", "colis", "coller",
    "collier", "colline", "combler", "commande", "commencer", "comment", "commerce", "communion", "complet",
    "composer", "comte", "comète", "concert", "conclure", "confiance", "confus", "congrès", "consacrer",
    "conserver", "consoler", "constant", "constater", "consulter", "contact", "content", "contenter",
    "conter", "continent", "continuel", "continuer", "contraire", "contrée", "convertir", "coquille",
    "corridor", "corriger", "coucher", "courageux", "courant", "couronne", "coussin", "couteau", "couvent",
    "couvercle", "coûter", "craindre", "crayon", "creux", "croisade", "croiser", "croissant", "croquer",
    "croître", "croûte", "cruel", "cruelle", "crèche", "crème", "créer", "crêpe", "culotte", "curieux",
    "curiosité", "cygne", "céder", "célèbre", "célébrer", "cérémonie", "d'après", "dangereux", "darder",
    "dater", "demander", "demeurer", "dentelle", "descendre", "dessert", "dessiner", "dessous", "deuxième",
    "diamant", "dicter", "différent", "direction", "discours", "dispenser", "distance", "distraire",
    "distrait", "domaine", "dompteur", "don", "dorer", "dortoir", "doucement", "douzaine", "doyen",
    "débarquer", "déboucher", "débris", "décharger", "déchirer", "décision", "découper", "découvrir",
    "défendre", "défenseur", "défiler", "défunt", "déjeuner", "délicieux", "déménager", "dépendre", "dépôt",
    "déranger", "désastre", "désert", "désespoir", "désigner", "désireux", "désobéir", "désordre", "détacher",
    "détourner", "effacer", "embellir", "embrasser", "empereur", "emploi", "emporter", "encadrer", "enchanté",
    "encourir", "endroit", "enfance", "enfermer", "enfoncer", "engloutir", "ennui", "enrichir", "enseigner",
    "ensemble", "entendre", "enterrer", "entonner", "entrain", "enveloppe", "envers", "envoi", "envoyer",
    "errer", "escalader", "espiègle", "espèce", "espérance", "essai", "essentiel", "eux", "exact", "examen",
    "excuse", "excuser", "exemple", "exercer", "exigence", "exiger", "exister", "expirer", "expliquer",
    "exposer", "exprimer", "exprès", "expédier", "exquis", "extraire", "extrémité", "extrême", "extérieur",
    "fabriquer", "faciliter", "facilité", "faiblesse", "fameux", "familial", "familier", "faner", "farouche",
    "fatiguer", "faucher", "faucheur", "fauteuil", "faux", "favori", "favoriser", "façade", "femelle",
    "fermeture", "fervent", "feuillage", "fiancé", "ficelle", "filer", "fixe", "fixer", "fièrement",
    "flamber", "flanc", "fleurir", "flotter", "flûte", "foncer", "fonction", "forestier", "fouetter",
    "fourneau", "fourrure", "foyer", "framboise", "franchise", "frapper", "frayeur", "fraîcheur", "friandise",
    "froisser", "frontière", "frotter", "frêle", "furieux", "fâcher", "gai", "gaieté", "galaxie", "garniture",
    "gaufre", "genou", "genêt", "giboulée", "glacer", "gland", "glissant", "glisser", "goal", "gourmand",
    "gouverner", "goûter", "gracieux", "graisse", "grandiose", "gratitude", "gravement", "griffer", "grille",
    "grillon", "grincer", "groseille", "grossier", "grouper", "grêle", "guerre", "guider", "guère",
    "guérison", "guêpe", "gymnase", "gâter", "généreux", "géranium", "gêner", "gîte", "habile", "habiter",
    "habitude", "halte", "hameau", "hangar", "hardi", "hasard", "hauteur", "heureux", "histoire", "honneur",
    "honorable", "honorer", "honteux", "horloge", "hors", "humain", "humble", "humidité", "hâter", "héros",
    "héroôque", "hôte", "hôtel", "ignorant", "ignorer", "illuminer", "imaginer", "immeuble", "immobile",
    "implorer", "important", "imposant", "imposer", "imprimer", "imprudent", "imprévu", "incendie",
    "incliner", "indiquer", "infirmier", "influence", "informer", "inférieur", "inonder", "inquiet",
    "insigne", "inspirer", "instant", "instruire", "intention", "interdire", "intérieur", "intérêt",
    "invention", "invoquer", "irriter", "isocèle", "ivresse", "jaloux", "jardinage", "jeunesse", "joyeux",
    "jugement", "kilomètre", "laborieux", "labourer", "lambeau", "lancer", "largement", "lasser", "lendemain",
    "lentement", "lierre", "lieue", "localité", "logis", "lointain", "longueur", "loyal", "lui-même",
    "lumineux", "lâcher", "madeleine", "maint", "maintenir", "maire", "malheur", "malle", "mandarine",
    "manoeuvre", "manquer", "mansarde", "manteau", "maquette", "marchand", "maudire", "mauvais", "meilleur",
    "menacer", "mendiant", "mensonge", "menuisier", "meringue", "mettre", "mieux", "militaire", "mille",
    "millier", "million", "minuscule", "missel", "mission", "mobilier", "modérer", "moins", "moisson",
    "molécule", "monsieur", "montant", "montrer", "monument", "moral", "mousse", "moyen", "moyenne", "muguet",
    "mystère", "mâchoire", "mât", "mécanique", "méchant", "mécontent", "médaille", "médaillon", "méfiance",
    "mélanger", "mélodieux", "mérite", "mêler", "mûr", "mûrir", "naissance", "naître", "neutron", "neveu",
    "nièce", "noeud", "noircir", "noisette", "noix", "nombreux", "nouille", "nouveau", "nouvelle", "novembre",
    "noyer", "nullement", "obscur", "obscurité", "obstacle", "obéissant", "occuper", "oeil", "officier",
    "offrir", "omelette", "opinion", "orchestre", "ordinaire", "ordonner", "organiser", "orgueil", "ornement",
    "orphelin", "orée", "oser", "paix", "paletot", "panorama", "pantalon", "papillon", "parallèle",
    "parapluie", "pardonner", "pareil", "parer", "paresse", "parlement", "parmi", "paroisse", "parsemer",
    "passage", "passant", "passion", "paternel", "patronage", "pavillon", "payer", "paysage", "paysan",
    "paître", "peindre", "peiner", "peintre", "peinture", "pencher", "penser", "percer", "permettre",
    "perpétuel", "personnel", "persuader", "pharmacie", "phrase", "pieux", "pipette", "pis", "plafond",
    "plaindre", "plancher", "pli", "plupart", "plusieurs", "poids", "poignée", "poing", "pois", "pommier",
    "portrait", "position", "possible", "poubelle", "poursuite", "pourtant", "pousser", "poussin",
    "poussière", "poète", "poêle", "presser", "princesse", "printemps", "privation", "prix", "prochain",
    "proclamer", "procéder", "programme", "progrès", "projet", "projeter", "prolonger", "promeneur",
    "promesse", "prononcer", "propice", "propriété", "proton", "provision", "provoquer", "pré", "précieux",
    "précéder", "préférer", "présenter", "préserver", "président", "prétendre", "prêter", "public",
    "puissance", "puissant", "punition", "pécher", "pédiatre", "pénitence", "quai", "quant", "quarante",
    "quatrième", "question", "queue", "quitter", "raconter", "radieux", "ranger", "rapidité", "rapiécer",
    "raquette", "rassurer", "rater", "ravissant", "rayon", "rebelle", "recherche", "recours", "recouvrir",
    "redoubler", "redouter", "refléter", "refroidir", "regagner", "rejoindre", "relation", "religieux",
    "remarquer", "remercier", "remettre", "remonter", "remplacer", "remporter", "renoncer", "renoncule",
    "renouveau", "rentrée", "renverser", "repasser", "reprocher", "respecter", "retomber", "retourner",
    "retrouver", "rhume", "richesse", "rigoureux", "rondelle", "rossignol", "rouille", "rouleau", "roulotte",
    "roux", "royal", "royaume", "ruisseau", "réaliser", "réalité", "récit", "réciter", "réel", "réfléchir",
    "régiment", "révéler", "rêver", "rôder", "rôti", "s'enfuir", "s'envoler", "s'écrier", "sacrement",
    "sacrifice", "sacrifier", "sagement", "sagesse", "sanglot", "satellite", "satisfait", "sauf", "sautiller",
    "savourer", "savoureux", "scier", "scène", "secours", "seigneur", "semblable", "sembler", "sens",
    "sentiment", "septembre", "serein", "sermon", "serrure", "serviette", "seulement", "signaler",
    "signifier", "sillon", "sinistre", "situation", "six", "soigner", "solitaire", "sonnette", "souci",
    "soudain", "souffle", "souffrir", "souhait", "soulager", "soulever", "soumettre", "soupirer", "souriant",
    "souvent", "souverain", "spacieux", "spectacle", "sphère", "spirituel", "splendeur", "spécial",
    "studieux", "style", "suc", "succéder", "sucer", "supérieur", "surmonter", "sursaut", "sursauter",
    "suspendre", "symphonie", "système", "séance", "sécher", "sécurité", "sérieux", "sévère", "sûr", "tacher",
    "tailleur", "talus", "taper", "taquiner", "tendresse", "tentation", "tenter", "terrain", "terrestre",
    "terreur", "terrible", "terrier", "thé", "tissu", "toilette", "tonneau", "tort", "touffe", "toujours",
    "tourment", "tournant", "toux", "tracer", "trait", "traiter", "trajet", "trancher", "transport",
    "travers", "traîner", "trembler", "tremper", "trimestre", "triomphe", "tristesse", "troisième",
    "trompette", "troupeau", "tunnel", "tuyau", "type", "tâcher", "télescope", "téléphone", "témoigner",
    "univers", "user", "utiliser", "vacances", "vaillant", "vain", "vaincre", "vanter", "veille", "veiller",
    "velours", "vengeance", "ver", "verdâtre", "vermeil", "vermillon", "vers", "vieil", "vigoureux", "voeu",
    "voix", "voyage", "voyager", "voûte", "vrai", "vraiment", "véhicule", "vêpres", "vêtement", "vêtir",
    "yeux", "âgé", "ébats", "échanger", "échec", "écho", "éclaircir", "éclairer", "éclatant", "éclipse",
    "économie", "écorce", "écraser", "éducation", "égal", "également", "égalité", "égard", "élan", "élégance",
    "éléphant", "émotion", "énergique", "épi", "époux", "éprouver", "équilibre", "équipage", "ériger",
    "étendre", "éternité", "étincelle", "étiquette", "étonner", "étranger", "étudiant", "évangile",
    "éveiller", "évidence", "évêque", "ôter"
  ],
  "CM1": [
    "abaisser", "abandonner", "abbaye", "abcès", "abondamment", "abrupt", "absolument", "absolutisme",
    "accabler", "accepter", "acclamation", "accompagner", "accomplir", "accourir", "accrocher", "accueil",
    "accueillir", "acheminer", "acquitter", "acquérir", "actuellement", "admettre", "administration",
    "administrer", "admiration", "adversaire", "affairé", "affectueux", "affliger", "affreux", "agréablement",
    "agrémenter", "aiguiser", "ailleurs", "aisance", "aisément", "alentours", "algorithme", "alias", "alibi",
    "aligner", "allemand", "allergie", "allégresse", "alpin", "ambulance", "amicalement", "américain",
    "anesthésie", "angoisse", "anneau", "annoncer", "anxieux", "apercevoir", "apostolique", "apostrophe",
    "apparaître", "apparemment", "apparition", "appartement", "appartenir", "appeler", "applaudir",
    "application", "appliquer", "apprendre", "approuver", "apprécier", "apprêter", "appuyer", "appétissant",
    "appétit", "après-midi", "arc-en-ciel", "architecte", "archéologie", "argenter", "argot", "aride",
    "arranger", "arrondir", "arrondissement", "arrêter", "arène", "arête", "asphyxie", "assaut", "assembler",
    "asseoir", "assiette", "associer", "astronaute", "astéroïde", "asymétrique", "athlète", "atmosphère",
    "attachement", "attacher", "attarder", "atteindre", "atteler", "attente", "attentivement", "atterrir",
    "attester", "attrait", "attraper", "attrister", "au-dessus", "augmenter", "aujourd'hui", "auparavant",
    "automobile", "avantageux", "avare", "aventurer", "avide", "baigner", "balançoire", "balayer", "baptiser",
    "barbu", "baril", "barrage", "barreau", "basse-cour", "berge", "bibliothécaire", "biceps", "bicyclette",
    "bidon", "bien-aimé", "bien-être", "bienfaisant", "bienfaiteur", "bienheureux", "bilan", "bison",
    "bizarre", "blesser", "blâme", "blême", "bocal", "bosselé", "botanique", "bouleau", "boulevard",
    "bouleverser", "bourdonnement", "bourdonner", "bourgeois", "bourgeoisie", "bourgeonner", "bourgmestre",
    "bourrasque", "bousculer", "bride", "brillant", "briller", "brouillard", "brune", "brusquement",
    "bulletin", "buste", "butin", "bénin", "bénit", "bénédiction", "bûcheron", "cache-cache", "caillou",
    "calendrier", "caler", "campagnard", "captif", "caresse", "caresser", "cargo", "carpe", "carrefour",
    "caser", "catastrophe", "catholique", "cathédrale", "catéchisme", "caviar", "ceinture", "centimètre",
    "cependant", "cerne", "chaland", "championnat", "changement", "charbonnage", "charcuterie", "charlatan",
    "charrette", "charrue", "chirurgien", "chocolaterie", "choir", "chronomètre", "chrysalide", "chrétien",
    "ci-joint", "cidre", "cierge", "circulation", "ciseaux", "citoyenneté", "clebs", "clergé", "clodo",
    "clémentine", "coccinelle", "cocon", "coefficient", "collection", "collège", "colon", "colonne",
    "combattre", "commandant", "commander", "commencement", "commercial", "commerçant", "commettre",
    "commode", "communal", "communiant", "communier", "communiquer", "comparaison", "compassion",
    "compliquer", "complètement", "compléter", "composition", "comprendre", "compte", "compter",
    "compétition", "concerner", "concours", "condamner", "condisciple", "condition", "confesser",
    "conformément", "conférence", "conjugaison", "connaître", "conquérir", "conscience", "conseiller",
    "consentement", "consentir", "considérable", "considérer", "consister", "consolation", "constamment",
    "constituer", "construction", "construire", "conséquence", "contempler", "continuellement", "contrarier",
    "convaincre", "conversation", "conviction", "coquelicot", "cordialement", "cordonnier", "corolle",
    "correction", "corse", "courageusement", "couronner", "courrier", "craquement", "croissance", "crucifix",
    "crépuscule", "crête", "cueillette", "cueillir", "cuiller", "cuillère", "cuisinière", "cuite",
    "cultivateur", "curer", "cycliste", "cylindre", "câble", "d'abord", "daigner", "damer", "demoiselle",
    "dernièrement", "derrière", "descente", "description", "dessein", "diagnostic", "dictionnaire",
    "difficile", "difficulté", "différence", "différer", "dilemme", "dimension", "discussion", "disparaître",
    "disparition", "disperser", "disposition", "dissiper", "distinction", "distinguer", "distraction",
    "distribuer", "distribution", "dommage", "dossier", "dresser", "durcir", "débattre", "déception",
    "déchaîner", "déclic", "décourager", "dédaigner", "délaisser", "démocratie", "démontrer", "dépasser",
    "déployer", "dépouiller", "dépêcher", "dérouler", "désaltérer", "désespérer", "déshabiller", "désolation",
    "désormais", "déterminer", "développement", "développer", "dévouement", "effectuer", "effrayer",
    "effroyable", "emballer", "embarquer", "embarrasser", "embaumer", "embrouille", "emmener", "emplacement",
    "employer", "employé", "empêcher", "encombrer", "encourager", "endosser", "endurance", "enflammer",
    "enluminure", "ennuyer", "ennuyeux", "enquête", "enseignement", "ensoleillé", "entasser", "enterrement",
    "entièrement", "entourer", "entraîner", "entretien", "envahir", "envelopper", "environnement",
    "environner", "essayer", "essuyer", "exactement", "exactitude", "examiner", "exaucer", "excellence",
    "excellent", "exceptionnel", "exciter", "exclamation", "excursion", "exemplaire", "exercice", "existence",
    "explication", "exploration", "exposition", "expression", "expédition", "expérience", "exécuter",
    "exécution", "fable", "fabrication", "facilement", "farcir", "façonner", "ferraille", "fibre", "fillette",
    "filleul", "finalement", "fiole", "firmament", "flair", "flatter", "flatteur", "flirt", "formel",
    "fouiller", "fourniture", "fourrer", "franchement", "français", "fraternité", "frigo", "frire",
    "frissonner", "fréquent", "fréquenter", "furtif", "fâcheux", "féliciter", "féodalité", "gaiement",
    "gambader", "gargouille", "gazouillement", "gazouiller", "gentiment", "germe", "gibecière", "gifle",
    "gigantesque", "glissoire", "globe", "golfe", "gonfler", "gourmandise", "goutte", "gouvernement", "grade",
    "grand-maman", "grand-mère", "grand-père", "granit", "gratis", "gratter", "gravitation", "grelotter",
    "groseillier", "guetter", "guichet", "gymnastique", "généralement", "générosité", "géographie", "gésir",
    "habileté", "habiller", "habitant", "habitation", "habituel", "habituer", "haillon", "haleine",
    "hanneton", "harmonieux", "hausser", "hermine", "heureusement", "heurter", "hexagone", "hirondelle",
    "hiéroglyphe", "hommage", "honnête", "horizon", "horreur", "horrible", "houille", "humanisme", "humanité",
    "hydrogène", "hygiène", "hypocrite", "hypothèse", "hypoténuse", "hyène", "hélicoptère", "hémisphère",
    "hémorragie", "hérissé", "hésiter", "illusion", "illustre", "illustrer", "imagination", "immaculé",
    "immense", "immédiatement", "impatience", "impatient", "imperméable", "importance", "importer",
    "impossible", "impression", "imprimerie", "imprudence", "incident", "indication", "indifférent",
    "indispensable", "industriel", "indépendance", "infiniment", "infirmière", "ingratitude", "innocent",
    "inondation", "inquiéter", "inquiétude", "insister", "insomnie", "installer", "institut", "instructif",
    "instruction", "intelligence", "intelligent", "intense", "interpeller", "interroger", "interrompre",
    "intrigué", "introduction", "introduire", "intéressant", "intéresser", "invitation", "jacinthe",
    "jaillir", "javel", "joncher", "jonquille", "joyeusement", "kermesse", "kilogramme", "laboratoire",
    "labyrinthe", "laisser", "lamentable", "larve", "lascar", "laïcité", "littérature", "longtemps",
    "longuement", "lèpre", "légal", "légèrement", "maintenant", "majestueux", "malette", "malheureusement",
    "malheureux", "manifester", "manoeuvrer", "manoir", "marchander", "marchandise", "marguerite", "marraine",
    "marron", "marronnier", "maussade", "maîtresse", "merveilleusement", "merveilleux", "messager", "micro",
    "microscope", "millimètre", "mixte", "moelleux", "moisir", "moissonneur", "moite", "monarchie",
    "monastère", "monnaie", "monseigneur", "mouiller", "multicolore", "mutuel", "myosotis", "myrtille",
    "mystérieux", "mythologie", "mélancolie", "mélancolique", "métaphore", "méthode", "météorite", "narcisse",
    "national", "naufrage", "naval", "nerveux", "nettoyer", "norme", "nourrir", "nourriture", "néanmoins",
    "nébuleuse", "nécessaire", "nécéssité", "négligence", "négligent", "négociant", "oasis", "obligeance",
    "obscurcir", "observation", "occasion", "occasionner", "occupation", "occurrence", "oeillet", "offenser",
    "oisillon", "olympique", "opposer", "opération", "ordinairement", "orgueilleux", "orthographe", "ouest",
    "oxygène", "paillette", "palme", "pamplemousse", "paranoïa", "paraître", "parchemin", "pardessus",
    "paresseux", "parfaitement", "paroi", "parrain", "parterre", "participer", "particulier",
    "particulièrement", "passager", "patience", "patio", "pensionnat", "perdrix", "perfection", "permission",
    "perroquet", "personnage", "personnalité", "perspective", "persévérer", "peste", "peut-être", "pharaon",
    "philosophe", "philosophie", "physique", "piazza", "pinceau", "pittoresque", "poilu", "porte-plume",
    "porto", "possession", "posséder", "poulailler", "poulain", "pourcentage", "pourrir", "poursuivre",
    "primevère", "principal", "principalement", "printanier", "prisonnier", "probabilité", "probablement",
    "procession", "prodigieux", "prodiguer", "professeur", "profession", "professionnel", "profondément",
    "promettre", "prompt", "propriétaire", "prospérité", "protection", "providence", "précaution",
    "précipiter", "précisément", "précédent", "préférence", "préoccuper", "préparatif", "préparation",
    "psychiatre", "psychologie", "puéril", "pâquerette", "pâtisserie", "pénal", "péniblement", "périlleux",
    "périmètre", "quantité", "quartier", "quelconque", "quelqu'un", "quelquefois", "quinzaine", "quotidien",
    "rafle", "rafraîchir", "raisonnable", "ramasser", "rapidement", "rappeler", "rapport", "rapporter",
    "rapprocher", "rassembler", "rattraper", "rayonner", "rechercher", "recommander", "recommencer",
    "reconduire", "reconnaître", "recueillir", "recul", "redescendre", "redresser", "regretter",
    "relativement", "relief", "remarquable", "remerciement", "renaissance", "renaître", "rencontrer",
    "rendez-vous", "renfermer", "renouveler", "renouvellement", "renseignement", "renseigner", "renvoyer",
    "reparaître", "repli", "repousser", "représentation", "représenter", "respectueux", "resplendir",
    "responsabilité", "ressembler", "ressentir", "ressort", "ressource", "retrousser", "rhinocéros",
    "rhumatisme", "rituel", "rival", "ronronner", "rosir", "rouiller", "rugir", "ruisseler", "ruisselet",
    "rural", "rythme", "réception", "réchauffer", "récompense", "récompenser", "réconforter", "récréation",
    "réellement", "réfectoire", "réflexion", "régir", "régner", "régulièrement", "répandre", "république",
    "résigner", "résistance", "résolution", "résonner", "réussir", "réveiller", "révolution", "rôtir",
    "s'absenter", "s'agenouiller", "s'efforcer", "s'emparer", "s'empresser", "s'écrouler", "s'éloigner",
    "s'évanouir", "saigner", "salve", "satisfaction", "satisfaire", "science", "scientifique", "scintiller",
    "seigneurie", "sifflement", "siffler", "sifflet", "silencieusement", "silencieux", "silhouette",
    "sillonner", "simplement", "simplicité", "sincèrement", "sincérité", "soigneusement", "soigneux", "solde",
    "solennel", "solliciter", "solstice", "sommeil", "souffler", "souffrance", "souhaiter", "souiller",
    "soupçonner", "souterrain", "soutien", "soviet", "soyeux", "splendide", "spécialement", "stage", "stand",
    "stationner", "statistique", "store", "stupéfaction", "subitement", "succulent", "suffire", "suffisant",
    "supplier", "supporter", "supposer", "surprendre", "surveillance", "surveiller", "symbole", "sympathique",
    "symptôme", "symétrie", "séminaire", "sérieusement", "sévèrement", "sûrement", "tacheter", "tailler",
    "taillis", "tapisser", "tardif", "tarif", "tarir", "tartelette", "tellement", "température", "tendrement",
    "terne", "ternir", "terrasse", "thermomètre", "thérapie", "théâtre", "tibia", "tilleul", "tonnerre",
    "torrent", "torse", "touffu", "tourbillon", "tourmenter", "tournoyer", "toutefois", "tracé",
    "traditionnel", "traitement", "trajectoire", "tranquille", "tranquillement", "transformation",
    "transformer", "transmettre", "transparent", "transporter", "travailler", "travailleur", "traîneau",
    "tressaillir", "trier", "triompher", "trotter", "trottoir", "turbulent", "télégramme", "téléphoner",
    "témoignage", "ténèbres", "universel", "vadrouille", "vagabond", "vainqueur", "vaisselle", "valse",
    "verbal", "verbe", "verdoyant", "vieillard", "vieillesse", "villageois", "viril", "virus", "visuel",
    "vital", "vocabulaire", "vocal", "volaille", "volontiers", "vulgaire", "végétation", "xénophobie",
    "zoologie", "ébranler", "échantillon", "éclabousser", "économiser", "écrivain", "écureuil", "électricité",
    "électrique", "électron", "émerveiller", "énormément", "épargner", "éphémère", "épouvantable",
    "épouvanter", "équilatéral", "équinoxe", "éteindre", "étincelant", "étinceler", "étonnement", "étouffer",
    "étrennes", "évidemment", "événement"
  ],
  "CM2": [
    "abandon", "abolir", "abonder", "abrutir", "abréger", "absoudre", "accélération", "acquis", "acrobate",
    "adoptif", "adorable", "advenir", "adverse", "adéquat", "affectionner", "affectueusement", "agenda",
    "agilité", "agonie", "agricole", "ajuster", "alarme", "alarmer", "alterner", "altitude", "altérer",
    "amante", "amarre", "ambigu", "amertume", "ameuter", "amiral", "amorce", "amorcer", "amortir", "ananas",
    "ancrer", "anecdote", "anniversaire", "anodin", "anormal", "antibiotique", "antipathique", "aplatir",
    "aplomb", "appelé", "aptitude", "arachnophobie", "arcade", "archive", "argenté", "argile", "aristocratie",
    "armure", "arnaque", "arsenal", "artisan", "artère", "asperge", "asperger", "aspirine", "assise",
    "astuce", "augure", "auréole", "austère", "autocar", "avancée", "avarice", "avatar", "avidité", "avérer",
    "bafouer", "balade", "ballet", "bambou", "banalité", "bannir", "barbare", "barbarie", "barbier", "barder",
    "baroque", "bascule", "basque", "battue", "bavard", "baveux", "bavure", "bestial", "bestiole", "biberon",
    "bibliothèque", "biblique", "bienveillance", "bienveillant", "bitume", "blaguer", "blinder", "blâmer",
    "bobine", "boiter", "bomber", "borner", "botter", "bouclier", "boudin", "boulet", "boulon", "bourbon",
    "bourdon", "boxeur", "braise", "brancard", "brasier", "braver", "bravoure", "brevet", "bricole",
    "bricoler", "broche", "bronzer", "brusquer", "budget", "buveur", "bâcler", "bélier", "bûcher", "cabaret",
    "cachot", "cadence", "cageot", "cajoler", "calepin", "calibre", "calligraphie", "calomnie", "calèche",
    "camelote", "candeur", "caniche", "cantine", "capsule", "capter", "captiver", "capturer", "carafe",
    "carapace", "caravane", "cardinal", "carnage", "carnaval", "carrer", "casbah", "cascade", "casier",
    "casquer", "cavale", "cavaler", "cavalier", "caveau", "censure", "certainement", "chaire", "chalet",
    "change", "chargeur", "charnel", "chaste", "chasteté", "chaton", "chef-d'oeuvre", "chenil", "chevelu",
    "chiche", "chichi", "chimie", "chimère", "chlorophylle", "chrysanthème", "châtier", "chèque", "chômage",
    "chômeur", "cigale", "cirage", "circonstance", "circuit", "civière", "clamer", "claustrophobie",
    "clavier", "clique", "clochard", "cloison", "cloque", "clébard", "cocher", "collet", "colombe",
    "colorier", "coltiner", "combine", "comique", "commandement", "commis", "communication", "compact",
    "compote", "compère", "concept", "condoléances", "conduit", "confectionner", "conforme", "conjugal",
    "connaissance", "console", "constellation", "constitution", "consul", "conteur", "continu", "contour",
    "convier", "coquin", "cornet", "correct", "correspondance", "corsage", "cosmique", "costard", "costaud",
    "couiner", "couplet", "coupole", "courtois", "couscous", "crachat", "craintif", "crampe", "crapaud",
    "crasse", "cratère", "cribler", "criminel", "crinière", "crique", "crisper", "croiseur", "croisière",
    "croquis", "crosse", "crouler", "croupir", "croyable", "croyant", "crypte", "créneau", "crépiter",
    "culbuter", "culturel", "cyclone", "cynisme", "cécité", "cérébral", "côtoyer", "daller", "damner",
    "denrée", "densité", "dentiste", "devise", "difficilement", "digérer", "dilater", "diluer", "diplôme",
    "disant", "distant", "divertir", "divinité", "divorcer", "domino", "donjon", "donnée", "dormant",
    "douane", "doublure", "drague", "draguer", "dragée", "droguer", "druide", "durable", "dureté", "débiner",
    "débuter", "décalage", "déceler", "décent", "décerner", "déchet", "décimer", "décisif", "déclin",
    "décliner", "décret", "décréter", "dédier", "déduire", "déesse", "défait", "déferler", "déformer",
    "dégaine", "dégrader", "déguster", "déjouer", "délier", "délirer", "déloger", "déluge", "démener",
    "dément", "démentir", "démerder", "démêler", "dénouer", "dépense", "déplorer", "déporter", "dépourvu",
    "déprimer", "dépêche", "déraper", "dérision", "dérive", "dériver", "déroute", "désarmer", "déserter",
    "désobéissance", "désobéissant", "détaler", "détecter", "détritus", "dévaler", "dévaster", "déverser",
    "dévier", "dévêtir", "empiler", "empressement", "encens", "enclin", "enclos", "encyclopédie", "enduire",
    "endurer", "enfler", "enivrer", "enjoué", "enlacer", "enrager", "ensuivre", "enthousiasme",
    "entraînement", "entêter", "envoyé", "escadre", "escadron", "escalade", "escale", "escapade", "escorte",
    "escorter", "escouade", "escroc", "exalter", "exiler", "expert", "extase", "extraordinaire", "faction",
    "facture", "faiblir", "faisan", "faiseur", "famine", "fanfare", "fantasme", "fardeau", "fatalité",
    "faucon", "fermeté", "fertile", "festin", "festival", "feutre", "fiacre", "fiancer", "fiction", "figuier",
    "filant", "filtrer", "finance", "flagrant", "flairer", "flasque", "flexible", "flirter", "fluide",
    "flâner", "fléchir", "flétrir", "forain", "forfait", "format", "formuler", "fortuit", "fortuné", "forçat",
    "fougue", "foulard", "fouler", "fourche", "fourgon", "fourmillière", "fracas", "fragment", "frappe",
    "fraternel", "fraude", "frayer", "fresque", "friser", "friture", "frivole", "froideur", "frénésie",
    "frôler", "fugitif", "fumant", "funeste", "fusion", "futile", "fuyant", "félicité", "féminité",
    "férocité", "fétiche", "gaffer", "galant", "galeux", "galoper", "gammée", "garnison", "gaulois",
    "gencive", "gendre", "geôlier", "gicler", "gigoter", "glacial", "glacier", "glaise", "glaive", "glande",
    "glaner", "glauque", "glaçon", "gluant", "gobelet", "gondole", "gorger", "gosier", "goudron", "gourer",
    "gradin", "gramme", "gravier", "grimace", "griser", "gruyère", "guidon", "gâchis", "gâteux", "gérant",
    "homard", "hostie", "huître", "impossibilité", "inconvénient", "indemne", "indice", "indirect", "infect",
    "infime", "infâme", "initial", "initiale", "initier", "intellectuel", "interne", "interruption",
    "intégral", "inverse", "investir", "invite", "inédit", "irréel", "jargon", "jasmin", "jauger", "jubiler",
    "jumeau", "jungle", "juvénile", "kinésithérapeute", "lagune", "laideur", "landau", "languir", "largeur",
    "larguer", "latéral", "laurier", "lavabo", "lavage", "lavande", "levier", "liasse", "libéral", "licence",
    "ligoter", "limace", "limonade", "liqueur", "livret", "livreur", "longue", "loterie", "loubard", "louche",
    "loulou", "loyauté", "lucide", "lucidité", "lunaire", "lustre", "lycéen", "lâcheté", "léguer", "légèreté",
    "macabre", "madone", "maigrir", "maladif", "malfrat", "malice", "malmener", "malsain", "mander",
    "mangeur", "maritime", "marmite", "marteler", "martial", "martyre", "marécage", "maréchal", "masquer",
    "matelot", "maturité", "matériau", "meneur", "merlan", "mesquin", "miauler", "microbe", "mijoter",
    "milice", "militer", "minéral", "mirage", "missionnaire", "mitard", "modeler", "moelle", "moniteur",
    "monopole", "monture", "montée", "moralité", "morgue", "morose", "morsure", "mortier", "mosquée",
    "motard", "mouler", "musulman", "mutiler", "mécano", "médiocre", "médiéval", "méduse", "méfiant",
    "mémère", "nageur", "naguère", "narguer", "narine", "nicher", "nombril", "notoire", "nounou", "nuance",
    "nuptial", "néfaste", "négatif", "objectif", "obséder", "ophtalmologue", "orateur", "orbite", "oriental",
    "orifice", "originel", "orteil", "orthophoniste", "outrage", "paisiblement", "palace", "palier",
    "palmier", "palper", "palpiter", "panoplie", "panser", "pantin", "par-ci", "parader", "parage",
    "parallélépipède", "parenté", "parisien", "parlant", "parloir", "partage", "passif", "patiner", "paumer",
    "peinard", "peloter", "peluche", "penseur", "pensionnaire", "percée", "perfide", "perfidie", "permis",
    "pesant", "photographie", "photographier", "photosynthèse", "pianiste", "piaule", "picoler", "pilier",
    "piloter", "piment", "pincée", "pioche", "piquet", "piston", "pivoter", "piètre", "piéger", "planque",
    "platine", "plombe", "plonge", "plongée", "plumer", "poigne", "poivre", "policier", "pomper", "pompon",
    "ponton", "porche", "portant", "portefeuille", "portion", "positif", "posture", "potage", "poulpe",
    "prenant", "prestige", "priorité", "priser", "procédé", "prodige", "profiler", "promis", "propager",
    "proportionnalité", "proprio", "prospère", "protestantisme", "pruneau", "précoce", "prédire", "préfet",
    "préjugé", "prélever", "présage", "présider", "présumer", "psaume", "pudique", "puiser", "punaise",
    "purger", "puzzle", "pâleur", "pâturage", "pèlerin", "pédaler", "péniche", "pépère", "pétard", "pétrin",
    "quatuor", "quinte", "rabbin", "racler", "raclée", "radeau", "radical", "rafale", "rafler", "ragoût",
    "rajeunir", "rangée", "rappel", "ration", "ravager", "ravaler", "raviver", "rayure", "rebondir", "rebord",
    "receler", "recoin", "recommandation", "reconnaissance", "reconnaissant", "recopier", "record", "recrue",
    "recruter", "recréer", "regorger", "rejeton", "relais", "relater", "relique", "relâche", "relève",
    "remarier", "remiser", "remous", "rempart", "remédier", "renouer", "renvoi", "repaire", "reparler",
    "replacer", "repris", "représentant", "repère", "requérir", "respectif", "restant", "retaper",
    "retardataire", "retenue", "retracer", "retrait", "revers", "revient", "rez-de-chaussée", "ricaner",
    "rigide", "rigolade", "rigolo", "rigueur", "rincer", "riposter", "risible", "rivalité", "rizière",
    "romance", "rouage", "rougeur", "routier", "ruminer", "réalisme", "réaliste", "réclame", "réduit",
    "réforme", "référer", "réprimer", "réputer", "réservoir", "résider", "résulter", "résumé", "rétrécir",
    "réviser", "révision", "révolter", "révolu", "rêveur", "sablier", "sachet", "salive", "sangle",
    "sarcasme", "sardine", "saturer", "sauveur", "saveur", "scotch", "scribe", "scruter", "scénario",
    "semence", "sensuel", "servile", "sierra", "simagrée", "simuler", "siroter", "sixième", "siéger",
    "slogan", "solaire", "solder", "sonder", "souche", "souder", "soufre", "soumis", "soutane",
    "souveraineté", "spasme", "spectre", "sphinx", "spirale", "spontané", "sportif", "spécimen", "stable",
    "statut", "steppe", "stimuler", "stupeur", "successivement", "sucrer", "sucrerie", "sultan", "surnom",
    "surplus", "sursis", "survie", "survoler", "suédois", "syrien", "sérénité", "tam-tam", "tampon",
    "tanière", "tapoter", "tatouer", "taudis", "taverne", "tenace", "tendon", "terminus", "timidité",
    "tirade", "tirage", "tireur", "tisane", "tituber", "tombée", "tonalité", "tondre", "torcher", "torchon",
    "tornade", "totalité", "toupie", "tourbillonner", "tournoi", "tracas", "traire", "traite", "tramer",
    "transe", "trappe", "trapèze", "traverse", "traîne", "traître", "trempe", "tresse", "tribune", "tricher",
    "triple", "tripoter", "trique", "trompe", "tropical", "troquer", "truand", "truffe", "truite", "truquer",
    "trèfle", "tumulte", "tunique", "unanime", "uniforme", "urbain", "vacant", "vacarme", "vaccin", "valide",
    "valser", "variété", "vassal", "vautour", "vautrer", "vengeur", "verdict", "vermine", "vernis", "verset",
    "vertical", "vertèbre", "vestige", "vibrer", "vipère", "virgule", "virilité", "vitalité", "vitrail",
    "voguer", "voilier", "volant", "volupté", "voyant", "voyeur", "véranda", "yaourt", "échine", "éclipser",
    "écrier", "écuyer", "édifice", "égaler", "égayer", "éjecter", "électeur", "élevage", "émaner", "émerger",
    "émeute", "émigrer", "épater", "éperon", "épicier", "épopée", "érotisme", "établissement", "étalon",
    "éteint", "éternuer", "étoilé", "étourdir", "évacuer", "évaluer"
  ],
  "Collège": [
    "abdiquer", "ablution", "abreuvoir", "acariâtre", "achélème", "acrobatie", "admiratif", "adoption",
    "adorateur", "adultère", "adversité", "affectif", "affermir", "agitateur", "aigrelet", "aimanter",
    "alanguir", "alarmant", "alchimie", "algarade", "algérien", "almanach", "alourdir", "alpaguer",
    "alsacien", "aléatoire", "amalgame", "amandier", "amenuiser", "amerloque", "amirauté", "amnistie",
    "analogie", "analogue", "animateur", "animosité", "anomalie", "antichar", "antilope", "antipode",
    "aquatique", "arabesque", "arbalète", "archiduc", "archipel", "armateur", "armature", "armoirie",
    "armurier", "arquebuse", "arrosoir", "artisanal", "asiatique", "aspérité", "asservir", "asticoter",
    "atrocité", "auditoire", "auréoler", "austérité", "automate", "automnal", "autonome", "aversion",
    "aérogare", "aéroplane", "babouche", "bachelier", "balafrer", "balancier", "balayeur", "balbutier",
    "baldaquin", "baliverne", "baluchon", "banquise", "barbaque", "barbiche", "barboter", "baromètre",
    "batelier", "baudrier", "bavarois", "bergerie", "berlingot", "berlinois", "beuverie", "bifurquer",
    "bigorneau", "bijoutier", "binoclard", "biscornu", "biscotte", "bistouri", "bleuâtre", "blondeur",
    "boiserie", "bouderie", "bougeoir", "bourgade", "branchage", "brassard", "bravement", "breloque",
    "breuvage", "bricolage", "brodequin", "broderie", "bronchite", "bronzage", "brunâtre", "bréviaire",
    "buanderie", "burlesque", "bâtardise", "béatitude", "bénitier", "bénévole", "cabriolet", "cachemire",
    "cacheter", "cadastral", "cadastre", "cafetier", "calamité", "calciner", "calembour", "calomnier",
    "calvitie", "cambouis", "camembert", "camisole", "campanile", "canadien", "canaliser", "canicule",
    "canotier", "capeline", "captivant", "caqueter", "caracoler", "carcéral", "carlingue", "carpette",
    "cascader", "catacombe", "cataracte", "causerie", "cavalcade", "censurer", "centième", "certifier",
    "chagriner", "chaloupe", "champêtre", "chandail", "chanoine", "charabia", "charmeur", "charnier",
    "charnière", "charpente", "chasuble", "cheminer", "cheminot", "chevalet", "chevalin", "chevreau",
    "chicorée", "chimiste", "chuinter", "chérubin", "ciboulot", "cimenter", "cinéaste", "clairsemé",
    "clapoter", "clapotis", "classeur", "clavecin", "clepsydre", "clinique", "cliqueter", "cliquetis",
    "clocheton", "cloporte", "cloîtrer", "clémence", "clôturer", "coaguler", "cocotier", "colmater",
    "coloniser", "colporter", "comestible", "comparse", "compatir", "compulser", "comédien", "concerter",
    "concerto", "concilier", "concubin", "conforter", "conscrit", "consulat", "contexte", "converger",
    "converser", "convoyer", "convulsif", "cordelier", "cordialité", "cornette", "corniaud", "cornichon",
    "corporel", "corpulent", "corsaire", "corvette", "costumer", "coudrier", "couleuvre", "couperet",
    "courbure", "coursier", "coursive", "courtier", "courtine", "courtiser", "coutumier", "couvrant",
    "crachoter", "cramoisi", "craqueler", "cravache", "cravater", "crocheter", "croulant", "crécelle",
    "crédulité", "cuissard", "cuistance", "culinaire", "culminant", "cupidité", "dandiner", "derechef",
    "derviche", "desserte", "devanture", "dextérité", "diagonale", "dialecte", "dialoguer", "diamètre",
    "diaphane", "diatribe", "difforme", "digestif", "diligence", "diplomate", "directoire", "discorde",
    "discourir", "disculper", "disjoint", "disloquer", "disparate", "dispersion", "distancer", "district",
    "divergent", "divulguer", "djellaba", "docilité", "doctorat", "dodeliner", "doléance", "dominical",
    "donateur", "dorloter", "douanier", "douceâtre", "douzième", "draperie", "dressage", "droiture",
    "drugstore", "drôlerie", "dubitatif", "dynamite", "débandade", "débander", "débecter", "déblayer",
    "débouché", "déboucler", "débrider", "débusquer", "décamper", "décharner", "déclamer", "déclinant",
    "décocher", "décolorer", "décoratif", "découdre", "découpage", "décroiser", "décroître", "décupler",
    "dédicace", "dédoubler", "défensif", "défensive", "défiance", "défrayer", "défricher", "défroque",
    "déférence", "déférent", "dégainer", "dégauchir", "déglutir", "dégorger", "dégrafer", "dégriser",
    "déguerpir", "dégénérer", "délation", "délectable", "délecter", "délester", "délimiter", "déloquer",
    "démesuré", "démordre", "départir", "dépiauter", "déplaisir", "dépotoir", "déraciner", "dérapage",
    "dérobade", "désarmant", "désavouer", "désoeuvré", "désolant", "détraquer", "détremper", "détriment",
    "dévaliser", "dévorant", "effectif", "embardée", "emboîter", "empiéter", "empêtrer", "encolure",
    "endiguer", "endurcir", "enfilade", "enjamber", "enjambée", "enjôleur", "enlaidir", "entacher",
    "enticher", "entêtant", "enviable", "envoûter", "ermitage", "escabeau", "escamoter", "escarpin",
    "escrimer", "esgourde", "estimable", "estivant", "estourbir", "estuaire", "exaction", "excepter",
    "exclamer", "excusable", "existant", "exorciser", "exorcisme", "exotisme", "explicite", "explosif",
    "expulsion", "expéditif", "extasier", "exténuer", "exécrable", "exécutif", "faiblard", "fainéant",
    "famélique", "fanatique", "fanatisme", "fantasque", "fastueux", "fatalisme", "fataliste", "fatidique",
    "favorite", "fermenter", "figurine", "filament", "filiforme", "filigrane", "financer", "fioriture",
    "fixation", "flageoler", "flambant", "flambeur", "flancher", "flanelle", "floraison", "flotteur",
    "flânerie", "fondateur", "fournaise", "fracture", "fraîchir", "fricoter", "friction", "fringale",
    "fringant", "frivolité", "froidure", "frôlement", "fulgurant", "fulminer", "funambule", "fureteur",
    "furibond", "futilité", "fébrilité", "fécondité", "féerique", "féministe", "gabardine", "galopade",
    "galopant", "gamberge", "gamberger", "gangrène", "garnement", "gazogène", "genièvre", "glacière",
    "gladiateur", "glissade", "gloriole", "goguenard", "goinfrer", "gondoler", "graminée", "gratifier",
    "gratuité", "grenadier", "grenadine", "grimacer", "grimpant", "griserie", "grisâtre", "grosseur",
    "guimauve", "guimbarde", "guttural", "guéridon", "géniteur", "généralité", "havresac", "hivernal",
    "huitième", "imagerie", "imaginatif", "imbroglio", "impavide", "importun", "imposteur", "impropre",
    "impudeur", "impulsif", "inaction", "inarticulé", "incartade", "inchangé", "incolore", "incurable",
    "incursion", "incurver", "indemnité", "indicible", "indolent", "indéfini", "inespéré", "infamant",
    "infecter", "infester", "infidèle", "infinité", "infirmité", "infortuné", "infusion", "ingénier",
    "insipide", "insoluble", "insurger", "intenable", "intensif", "intermède", "intitulé", "inusable",
    "inutilité", "invective", "inversion", "invétéré", "inégalité", "ironiser", "jactance", "jalouser",
    "jardinet", "jardinière", "jaunâtre", "jointure", "jongleur", "juridique", "jérémiade", "laconique",
    "langueur", "languide", "largesse", "latitude", "libanais", "libertin", "limpidité", "linoléum",
    "liquéfier", "liturgie", "lourdeur", "louvoyer", "luminosité", "légalité", "légation", "législatif",
    "légitimer", "légitimité", "lézarder", "macaroni", "machinal", "magnolia", "maigreur", "majuscule",
    "malingre", "malpropre", "maléfice", "mandarin", "mandibule", "manigance", "manucure", "maquisard",
    "marchant", "marcheur", "margelle", "marginal", "marmelade", "marocain", "maroquin", "martinet",
    "marxisme", "marxiste", "mascarade", "mastiquer", "maugréer", "mauresque", "membrane", "mercerie",
    "meurtrir", "micheton", "milicien", "militant", "mimétisme", "minauder", "minimiser", "ministériel",
    "minorité", "minuterie", "miroitant", "miroiter", "mobilité", "modalité", "momentané", "momifier",
    "monarque", "mondanité", "monocorde", "monotonie", "monticule", "monétaire", "moulinet", "moustachu",
    "moutarde", "muscadet", "mâchefer", "médisance", "méditatif", "méprisable", "méprisant", "méridional",
    "méritant", "méritoire", "nageoire", "narquois", "nautique", "nestorien", "niaiserie", "noblement",
    "noirceur", "noirâtre", "nordique", "notifier", "notoriété", "nounours", "numéroter", "nénuphar",
    "objecter", "obliquer", "obnubiler", "obsédant", "obédience", "octogonal", "oisiveté", "ombilical",
    "omoplate", "ondulant", "opiniâtre", "opulence", "opérateur", "oratoire", "orchidée", "ordurier",
    "organique", "ostensoir", "outrance", "pacifier", "palabrer", "palpable", "pancréas", "pantomime",
    "papeterie", "paquetage", "parabole", "paradoxal", "parement", "parodier", "partance", "partisan",
    "partouze", "passoire", "pastèque", "patrimoine", "pavement", "pavoiser", "pentecôte", "perchoir",
    "percuter", "perdreau", "perpétrer", "perpétuité", "persuasif", "persuasion", "pianoter", "piqueter",
    "piécette", "piédestal", "placarder", "placette", "placidité", "plaisance", "planteur", "plastron",
    "platitude", "pleurant", "pluvieux", "poitrail", "ponctuel", "ponctuer", "populace", "popularité",
    "portatif", "portique", "postérieur", "postérité", "posément", "pouliche", "pourtour", "pradelle",
    "praticien", "prestance", "primordial", "princier", "prisunic", "procréer", "profaner", "profitable",
    "profusion", "proférer", "promiscuité", "promoteur", "pronostic", "prospérer", "prussien", "préalable",
    "préambule", "précaire", "précepte", "précepteur", "préjudice", "préjuger", "préluder", "présager",
    "prétexter", "prétoire", "prévaloir", "prêcheur", "psalmodier", "purgatoire", "puritain", "pébroque",
    "pédéraste", "péninsule", "pénétrant", "péquenot", "péripétie", "pétarade", "pétarader", "pétition",
    "quiétude", "quolibet", "rabrouer", "raclement", "racontar", "racornir", "radoucir", "rajuster",
    "rambarde", "rameuter", "rancunier", "raréfier", "ratatiner", "rebutant", "recenser", "receveur",
    "rechange", "recouper", "recourber", "recouvert", "recracher", "redingote", "reformer", "refréner",
    "regardant", "reliquat", "reluisant", "reléguer", "remontée", "remâcher", "renauder", "rencarder",
    "renchérir", "rengorger", "rentable", "renverse", "renâcler", "repartie", "repaître", "repiquer",
    "replanter", "repriser", "rescaper", "resurgir", "retouche", "retourne", "revenant", "ricanant",
    "ricocher", "ricochet", "rigidité", "rigolard", "ripoliner", "romancier", "rougeole", "rouspéter",
    "routinier", "rudiment", "rutilant", "râtelier", "régional", "régularité", "régénérer", "réitérer",
    "réprouver", "répudier", "répulsion", "résonance", "résorber", "rétorquer", "réverbère", "révoltant",
    "révulser", "sabotage", "sacrilège", "sacrément", "saladier", "salingue", "salpêtre", "salutaire",
    "samouraï", "sanitaire", "sarabande", "saugrenu", "saumâtre", "scorpion", "seizième", "serpenter",
    "servitude", "sibérien", "simulacre", "simultané", "singerie", "snobisme", "sobriquet", "sobriété",
    "solidité", "somnolent", "somnoler", "sonatine", "songerie", "sonorité", "soupente", "soupeser",
    "soupirail", "soupière", "sourdine", "souteneur", "soutirer", "sparadrap", "spécifier", "spéculer",
    "stagnant", "stalinien", "stigmate", "stimulant", "stratège", "strident", "stupéfier", "stérilité",
    "subalterne", "subjuguer", "subodorer", "subtilité", "subversif", "suintant", "surnager", "surplomb",
    "survenue", "survivant", "surélever", "suspense", "suspicion", "syndical", "sécréter", "séculaire",
    "séducteur", "sénéchal", "sépulture", "sévérité", "tabatière", "tabernacle", "tactique", "talisman",
    "tangible", "tantinet", "tapageur", "tarauder", "tartiner", "templier", "temporel", "tempérer",
    "tempêter", "tenancier", "tentacule", "tintouin", "titubant", "toboggan", "tonitruer", "tortueux",
    "traiteur", "trappeur", "traversin", "travestir", "traînant", "traîtrise", "triporteur", "triturer",
    "tromperie", "troufion", "trémière", "trésorier", "tunisien", "turpitude", "turquoise", "tutélaire",
    "tyrolien", "télévisé", "ténacité", "ubiquité", "ultimatum", "ultérieur", "vacancier", "vacciner",
    "vaporiser", "variable", "variante", "vasistas", "ventouse", "vergogne", "vermoulu", "vertébral",
    "verveine", "vestibule", "veulerie", "vexation", "viennois", "vigilance", "vignoble", "violacer",
    "violoniste", "virginal", "virtuosité", "virulent", "viscéral", "visibilité", "vitamine", "vitrifier",
    "vivacité", "vociférer", "voilette", "voisiner", "volatile", "voltigeur", "volubile", "volubilité",
    "voracité", "végétatif", "vénitien", "véridique", "zigzaguer", "âprement", "éberluer", "ébéniste",
    "écarlate", "écarteler", "éclaircie", "éclaireur", "éclosion", "éconduire", "écorchure", "écourter",
    "écrasant", "écritoire", "édifiant", "églantine", "égoutier", "élasticité", "élastique", "élucider",
    "énervant", "énormité", "épiderme", "épilepsie", "épilogue", "épluchure", "équateur", "équation",
    "équatorial", "équestre", "équitable", "éraflure", "éruption", "étendard", "étrangeté", "évertuer"
  ],
  "Lycée": [
    "aberration", "abomination", "acceptation", "accessible", "accommoder", "accomplissement", "accouchement",
    "accroupir", "accroître", "accueillant", "accusation", "acharnement", "acquiescement", "acquiescer",
    "acquisition", "actionner", "administrateur", "administratif", "admirablement", "adolescence",
    "affaisser", "affectation", "affirmation", "affleurer", "affranchir", "affreusement", "affrontement",
    "affronter", "agenouiller", "agressivité", "agriculture", "aisselle", "alimentaire", "alimentation",
    "allitération", "alternative", "alternativement", "ambassadeur", "amoncellement", "amour-propre",
    "anachronisme", "anaphore", "andouille", "anguille", "antichambre", "anticiper",
    "anticonstitutionnellement", "antithèse", "antonyme", "aphorisme", "apocryphe", "aporie", "apothéose",
    "applaudissement", "apprentissage", "apprivoisement", "apprivoiser", "approbation", "approfondir",
    "approprier", "appréhender", "appréhension", "après-demain", "architecture", "archéologue", "archétype",
    "arrangement", "arrestation", "arrière-boutique", "arrière-grand-père", "arrière-pensée", "articulation",
    "artillerie", "artilleur", "assaillir", "assemblage", "assemblée", "assigner", "association", "assombrir",
    "assommer", "assourdissant", "asymptote", "asyndète", "attendrir", "attendrissement", "attraction",
    "attribut", "attribution", "au-dehors", "au-dessous", "augmentation", "authentique", "automatique",
    "automatiquement", "autorisation", "avant-garde", "avant-guerre", "avant-hier", "avant-poste",
    "avertissement", "aveuglement", "axiome", "bafouiller", "balancement", "ballotter", "barbouiller",
    "bassesse", "bastille", "bataillon", "baïonnette", "belle-fille", "bizarrement", "bombardement",
    "bouillant", "bouillie", "bouilloire", "bouillonner", "bouleversant", "bouleversement", "bousiller",
    "brailler", "brancardier", "bredouiller", "brouhaha", "brouiller", "broussaille", "bruissement",
    "bruyamment", "bureaucratie", "béquille", "c'est-à-dire", "cacophonie", "cambriolage", "cambrioleur",
    "camionnette", "cantonnement", "capitalisme", "capitulation", "caractéristique", "carrosse",
    "carrosserie", "carrousel", "casse-croûte", "catastrophique", "catharsis", "catégorique", "certes",
    "chamailler", "charpentier", "chatouiller", "chauve-souris", "cheminement", "chenille", "chiasme",
    "christianisme", "chromatographie", "chromosome", "chuchotement", "cinquantaine", "civilisation",
    "clandestinité", "cochonnerie", "coffre-fort", "collaborateur", "collaboration", "collectionner",
    "collectionneur", "combinaison", "commentaire", "commissaire", "commissariat", "commission", "commissure",
    "comparaître", "compartiment", "compensation", "complaisance", "complaisant", "complication",
    "comportement", "compositeur", "compromettre", "compréhensible", "compréhensif", "compréhension",
    "comptabilité", "concentration", "concomitamment", "concurrence", "condamnation", "condescendance",
    "condoléance", "confidentiel", "confirmation", "confrontation", "confusément", "conjecture",
    "consciencieusement", "conscient", "conservateur", "conservatoire", "considérablement", "considération",
    "consistance", "consommateur", "consommation", "conspiration", "constatation", "consternation",
    "consultatif", "consultation", "contemplation", "contemporain", "contentement", "contraction",
    "contradiction", "contradictoire", "contraindre", "contrairement", "contre-jour", "contremaître",
    "contribution", "convaincant", "convalescence", "convenablement", "conventionnel", "convocation",
    "coquetterie", "coquillage", "corbillard", "corollaire", "correctement", "correspondre", "corrompre",
    "corruption", "coïncidence", "crasseux", "croque-mort", "cruellement", "crépitement", "cuillerée",
    "curieusement", "célibataire", "d'emblée", "dahlia", "dangereusement", "davantage", "demi-cercle",
    "demi-douzaine", "demi-heure", "demi-siècle", "desserrer", "dessinateur", "destruction", "dialectique",
    "différemment", "différencier", "diplomatique", "discriminant", "discrètement", "distiller",
    "distinctement", "distraitement", "distributeur", "divertissement", "douillet", "douloureusement",
    "dysfonctionnement", "débarquement", "débarrasser", "déboutonner", "débrouiller", "déchiffrer",
    "déchiqueter", "déchirement", "décomposition", "déconcertant", "déconcerter", "découragement",
    "dédaigneux", "défaillance", "défaillir", "déferlement", "définitivement", "dégringoler", "déguisement",
    "dégât", "délibérément", "délicatement", "délicatesse", "délicieusement", "déliquescence", "démocratique",
    "démonstration", "déménagement", "dépens", "déplacement", "dérailler", "dérivée", "dérouiller",
    "déroulement", "désapprouver", "désastreux", "désespérément", "désinfecter", "désintéresser",
    "désinvolture", "détachement", "détailler", "détermination", "déterminisme", "eau-de-vie", "ecchymose",
    "effaroucher", "effectivement", "effervescence", "effleurer", "effondrement", "effondrer", "effraction",
    "effrayant", "effriter", "embarcation", "embarquement", "embarras", "embarrassant", "embouteillage",
    "embrasse", "embrouiller", "emmerdement", "empirisme", "employeur", "empoisonner", "empresser",
    "emprisonner", "encadrement", "enchantement", "enchaînement", "encouragement", "enfreindre", "engouffrer",
    "engourdissement", "engraisser", "enregistrer", "entaille", "enthousiasmer", "enthousiaste",
    "entre-temps", "entrebâiller", "entrechoquer", "entrecroiser", "entrepreneur", "entrouvrir",
    "envahisseur", "enzyme", "escadrille", "esclaffer", "escroquerie", "espadrille", "essentiellement",
    "essouffler", "esthétique", "euphonie", "euphémisme", "exaltation", "exaspération", "exceller",
    "exceptionnellement", "exclusivement", "exhaler", "existentialisme", "exploitation", "exponentielle",
    "expérimenter", "extinction", "extraordinairement", "extravagant", "faillite", "faine", "familiarité",
    "farfouiller", "fascination", "feuillet", "feuilleter", "feuilleton", "fluorescence", "fonctionnaire",
    "fonctionnement", "fonctionner", "fondamental", "fonds", "football", "formellement", "fossette",
    "fouillis", "fournisseur", "fraîchement", "froissement", "frustration", "frémissement", "fréquemment",
    "fréquentation", "furieusement", "furtivement", "fusillade", "garde-à-vous", "gaspiller", "gendarmerie",
    "gentilhomme", "gentillesse", "gothique", "gouttelette", "gouvernante", "graisseux", "grand-peine",
    "grandissant", "gratuitement", "griffonner", "grisaille", "grossesse", "grossièrement", "grossièreté",
    "grouillant", "grouillement", "grouiller", "grésiller", "guillotine", "gynécologue", "gémissement",
    "généreusement", "géométrique", "habituellement", "hallucination", "hargneux", "haussement",
    "haut-commissaire", "haut-parleur", "hebdomadaire", "herméneutique", "hollandais", "homosexualité",
    "homosexuel", "homéostasie", "hongrois", "honnêtement", "honnêteté", "horriblement", "hospitaliser",
    "hospitalité", "huissier", "humblement", "humiliation", "hygiénique", "hyperbole", "hyperbolique",
    "hypnotiser", "hypocrisie", "hystérie", "hystérique", "hédonisme", "hégémonie", "hérisser", "héroïque",
    "héroïsme", "héréditaire", "hésitation", "hétéroclite", "hôpital", "identification", "idéalisme",
    "illimité", "illisible", "illumination", "illusoire", "illustration", "immanence", "immobiliser",
    "immortalité", "impardonnable", "impatiemment", "impatienter", "imperceptible", "imperceptiblement",
    "impersonnel", "imperturbable", "impitoyable", "impressionnant", "impressionner", "imprégner",
    "imprévisible", "impuissance", "impénétrable", "impératrice", "inacceptable", "inaccessible",
    "inaltérable", "inauguration", "incandescence", "incandescent", "incarnation", "incertitude",
    "incomparable", "incompréhensible", "incompréhension", "inconcevable", "inconsciemment", "inconscience",
    "inconscient", "incroyablement", "incrédulité", "indestructible", "indifférence", "indignation",
    "indiscrétion", "indiscutable", "indubitablement", "indéfiniment", "indéfinissable", "indépendant",
    "inexplicable", "infaillible", "infatigable", "inflexible", "inflexion", "informateur", "inimaginable",
    "injonction", "inlassablement", "innombrable", "inquisition", "insaisissable", "inscription",
    "insensiblement", "insignifiant", "insouciance", "insoutenable", "inspection", "inspiration",
    "installation", "instantanément", "instinctif", "instinctivement", "institution", "insuffisance",
    "insuffisant", "insupportable", "inséparable", "intensément", "intercepter", "interdiction",
    "interlocuteur", "interminablement", "international", "interprétation", "interpréter", "interrogation",
    "interrogatoire", "intervention", "intolérable", "introuvable", "intégrale", "intérieurement",
    "inutilement", "invariablement", "investigation", "investissement", "involontaire", "invraisemblable",
    "inéluctable", "inéluctablement", "irremplaçable", "irresponsable", "irritation", "irruption",
    "irrémédiable", "irrémédiablement", "irréparable", "irréprochable", "irrésistible", "irrésistiblement",
    "journalisme", "jurisprudence", "justification", "lamentation", "lentille", "litote", "littéralement",
    "logarithme", "luminescence", "là-dessous", "là-dessus", "légionnaire", "machinalement", "magnétophone",
    "maisonnette", "maladroitement", "mallette", "malédiction", "mammouth", "manifestation", "manifestement",
    "maquillage", "maquiller", "marionnette", "matérialiser", "matérialisme", "mayonnaise", "maïeutique",
    "mentalement", "mentionner", "minutieusement", "miraculeusement", "miséricordieux", "mitochondrie",
    "mitrailler", "mitraillette", "mitrailleur", "mobilisation", "modification", "mollesse", "momentanément",
    "monstrueux", "mordiller", "mousquetaire", "municipalité", "music-hall", "mutuellement",
    "mystérieusement", "mythique", "méconnaissable", "méconnaître", "mécontentement", "méditerranéen",
    "mésaventure", "métamorphose", "métamorphoser", "métaphysique", "métonymie", "nationalisme",
    "nationalité", "nerveusement", "nettoyage", "neutraliser", "nihilisme", "nonchalance", "nostalgique",
    "nourrisson", "nécessairement", "négligeable", "négligemment", "négociation", "obscurément",
    "obsolescence", "obstination", "obstinément", "obséquieux", "officiellement", "offrande", "oligarchie",
    "ombrelle", "onctueux", "ontologie", "opposition", "oppresser", "oppression", "organisation",
    "orientation", "originalité", "orthodoxe", "osciller", "ostensiblement", "otorhinolaryngologiste",
    "ouvertement", "oxymore", "pagaille", "paillasse", "paillasson", "panthéon", "parachutiste",
    "paradoxalement", "parcours", "pareillement", "parenthèse", "paronomase", "participation",
    "particularité", "passe-temps", "passerelle", "passionnant", "passionnel", "passionner", "passionnément",
    "pastille", "pathétique", "patriotique", "patrouille", "pensivement", "perfectionner", "performance",
    "perplexité", "perpétuellement", "perquisition", "personnellement", "persécution", "petite-fille",
    "philosophique", "phonographe", "phosphorescence", "phosphorescent", "photographe", "physionomie",
    "physiquement", "phénomène", "phénoménologie", "piaillement", "piailler", "pique-nique", "piétinement",
    "plaisanterie", "plate-forme", "pleurnicher", "plébiscite", "pléonasme", "poisseux", "polynôme",
    "polysémie", "porte-monnaie", "possibilité", "posthume", "pourchasser", "poussiéreux", "pratiquement",
    "pressentiment", "prestigieux", "primitive", "privilégier", "procès-verbal", "progression",
    "progressivement", "prolongement", "prosopopée", "protestation", "provisoirement", "provocation",
    "précipitamment", "précipitation", "prémonition", "préoccupation", "prépondérance", "présentation",
    "présidentiel", "prétentieux", "psychanalyse", "psychiatrique", "psychologique", "psychologue",
    "publication", "publicitaire", "publiquement", "puits", "pull-over", "pusillanime", "pénitentiaire",
    "pénétration", "péremptoire", "périphrase", "quarantaine", "questionner", "quintessence",
    "quotidiennement", "racaille", "raccommoder", "raccompagner", "raccourcir", "raccrocher", "raffinement",
    "rageusement", "raisonnement", "randonnée", "rappliquer", "rapprochement", "rassemblement",
    "rationalisme", "rationnel", "ravissement", "ravitaillement", "ravitailler", "rayonnage", "rayonnant",
    "rayonnement", "reconnaissable", "reconstituer", "reconstruction", "reconstruire", "recroqueviller",
    "rectangulaire", "redressement", "regrettable", "rehausser", "remords", "remplacement", "remplaçant",
    "remue-ménage", "renoncement", "reproduction", "ressasser", "ressemblance", "ressentiment", "resserrer",
    "ressusciter", "restauration", "restriction", "retrouvaille", "revendication", "revendiquer", "rhabiller",
    "rhubarbe", "rhétorique", "ribosome", "ridiculiser", "rigoureusement", "ronronnement", "roupiller",
    "rugissement", "réalisation", "réapparaître", "réconciliation", "réconcilier", "réconfortant",
    "récurrence", "réfrigérateur", "référendum", "réglementaire", "réminiscence", "réprobation",
    "républicain", "réquisitionner", "résignation", "résurrection", "rétablissement", "rétroviseur",
    "réveillon", "révolutionnaire", "saillant", "sanction", "sans-pareil", "satisfaisant", "sauvagement",
    "sauvegarder", "scandaliser", "scepticisme", "schizophrénie", "sciemment", "scintillant", "secrètement",
    "sensationnel", "sensibilité", "serpillière", "siffloter", "signalement", "significatif", "signification",
    "simultanément", "singulièrement", "soixantaine", "solennellement", "sollicitude", "sommeiller",
    "somptueux", "sophisme", "soudainement", "soufflet", "souffrant", "soupçonneux", "sournoisement",
    "sous-lieutenant", "sous-officier", "sous-vêtement", "soutien-gorge", "spaghetti", "spectaculaire",
    "spontanément", "spécialiser", "spéculation", "station-service", "stochastique", "stoïcisme",
    "stratégique", "strictement", "stupidement", "stœchiométrie", "subrepticement", "successeur",
    "succession", "suffisamment", "superstitieux", "superstition", "suppliant", "supplication", "supplément",
    "supplémentaire", "supportable", "supposition", "supprimer", "sur-le-champ", "surhumain", "surlendemain",
    "surveillant", "susceptible", "syllogisme", "sympathie", "synecdoque", "systématiquement", "tambouriner",
    "tautologie", "tempérament", "terrasser", "terre-plein", "terriblement", "thermodynamique", "théocratie",
    "théologie", "théorique", "théorème", "tignasse", "tirailleur", "torpille", "tortiller", "totalitarisme",
    "touristique", "tout-puissant", "tranquillité", "transcendance", "transfigurer", "translucide",
    "transmission", "transparence", "transpercer", "tremblement", "triangulaire", "trigonométrie",
    "trouvaille", "télégraphier", "téléphonique", "tête-à-tête", "universitaire", "utilisation",
    "utilitarisme", "va-et-vient", "vacillant", "vaciller", "veilleur", "veilleuse", "verrouiller",
    "vertigineux", "violoncelle", "volontairement", "vraisemblable", "vraisemblablement", "vérification",
    "véritablement", "éblouissant", "éblouissement", "écarquiller", "échafaudage", "éclaboussure",
    "écroulement", "égratignure", "électromagnétisme", "électronique", "éloignement", "élémentaire",
    "émerveillement", "énigmatique", "éparpiller", "épicurisme", "épiphénomène", "épistémologie",
    "épouvantail", "équiprobable", "éternellement", "étrangement", "étroitement", "éventualité",
    "éventuellement"
  ],
};
const NIVEAUX = Object.keys(MOTS);
