// Listes de mots par niveau — français uniquement, accents inclus.
// Modifier librement : une entrée = un mot (ou un mot composé avec trait d'union / apostrophe).
const MOTS = {
  "CE1": [
    "papa","maman","chat","chien","lapin","poule","vache","cheval","mouton","cochon","canard","souris",
    "oiseau","poisson","école","maison","jardin","cuisine","chambre","table","chaise","porte","fenêtre",
    "lit","livre","cahier","crayon","stylo","gomme","règle","sac","pomme","poire","fraise","cerise",
    "banane","orange","citron","pain","lait","beurre","sucre","farine","gâteau","biscuit","sablé",
    "chocolat","bonbon","fromage","salade","carotte","soupe","soleil","lune","étoile","nuage","pluie",
    "neige","vent","ciel","mer","plage","sable","bateau","voiture","vélo","train","avion","route","pont",
    "arbre","fleur","feuille","forêt","montagne","rivière","roi","reine","prince","fée","dragon","château",
    "lundi","mardi","jeudi","matin","soir","nuit","jour","hiver","été","rouge","bleu","jaune","vert",
    "blanc","noir","grand","petit","joli","gentil","sage","content","bonjour","merci","main","pied","nez",
    "bras","tête","cœur","ballon","jouet","poupée","copain","frère","sœur","mamie","papi","bébé","gros",
    "haut","bas","chaud","froid","ours","loup","renard","tortue","zèbre","lion","singe","girafe","tigre"
  ],
  "CE2": [
    "printemps","automne","dimanche","mercredi","vendredi","samedi","semaine","histoire","musique","dessin",
    "cartable","tableau","maître","maîtresse","camarade","famille","cousin","cousine","grand-mère",
    "grand-père","éléphant","grenouille","papillon","abeille","araignée","escargot","hérisson","écureuil",
    "sanglier","chouette","hibou","aigle","dauphin","requin","baleine","légume","courgette","tomate",
    "haricot","poireau","champignon","citrouille","confiture","caramel","vanille","noisette","amande",
    "éclat","pépite","recette","cuillère","fourchette","couteau","assiette","serviette","bouteille",
    "casserole","chaussure","chaussette","pantalon","manteau","bonnet","écharpe","chapeau","lunettes",
    "peut-être","aujourd'hui","toujours","jamais","souvent","beaucoup","ensemble","pourquoi","comment",
    "combien","quelque","chaque","cadeau","anniversaire","bougie","chanson","guitare","tambour","magicien",
    "fantôme","monstre","pirate","trésor","épée","chevalier","princesse","couronne","voyage","vacances",
    "valise","piscine","chemin","village","campagne","ferme","tracteur","addition","problème","question",
    "réponse","exercice","silence","lecture","écriture","nombre","chiffre","quinze","trente","quarante",
    "douze","treize","seize","kangourou","crocodile","perroquet","pingouin","mouette","hirondelle",
    "phoque","panthère","dromadaire","hippopotame"
  ],
  "CM1": [
    "bibliothèque","dictionnaire","boulangerie","pâtisserie","charcuterie","pharmacie","hôpital","médecin",
    "infirmière","ambulance","accident","aventure","découverte","exploration","expérience","laboratoire",
    "scientifique","planète","système","océan","continent","volcan","tempête","orage","tonnerre","éclair",
    "arc-en-ciel","brouillard","température","thermomètre","maintenant","pourtant","cependant","autrefois",
    "longtemps","quelquefois","d'abord","ensuite","enfin","nouveau","ancien","énorme","minuscule",
    "magnifique","extraordinaire","gigantesque","mystérieux","courageux","dangereux","merveilleux",
    "excellent","différent","important","intéressant","nécessaire","silencieux","délicieux","curieux",
    "sérieux","joyeux","malheureux","heureux","nombreux","affreux","paresseux","généreux","chocolaterie",
    "gourmandise","friandise","meringue","croissant","brioche","madeleine","tartelette","framboise",
    "myrtille","groseille","abricot","pamplemousse","mandarine","clémentine","noix","châtaigne","marron",
    "potiron","aubergine","poivron","betterave","radis","navet","ceinture","bracelet","collier","bouton",
    "fermeture","poignée","escalier","couloir","grenier","garage","balcon","terrasse","immeuble",
    "appartement","quartier","boulevard","carrefour","trottoir","autobus","tramway","métro","hélicoptère",
    "fusée","satellite","astronaute","télescope","microscope","boussole","calendrier","horloge","chronomètre"
  ],
  "CM2": [
    "rythme","orchestre","chrysanthème","bibliothécaire","kilomètre","millimètre","parallèle","accueillir",
    "cueillir","ennuyeux","essentiel","exceptionnel","professionnel","traditionnel","personnalité",
    "responsabilité","hypothèse","symphonie","photographie","géographie","orthographe","conjugaison",
    "grammaire","vocabulaire","littérature","philosophie","démocratie","république","révolution",
    "indépendance","développement","environnement","gouvernement","parlement","immédiatement","évidemment",
    "apparemment","malheureusement","heureusement","particulièrement","connaissance","reconnaissance",
    "naissance","croissance","puissance","patience","science","conscience","ambiance","distance",
    "abondance","élégance","enfance","vengeance","méfiance","confiance","assurance","surveillance",
    "apparence","différence","conséquence","influence","violence","urgence","exigence","absence",
    "présence","prudence","évidence","silhouette","baguette","raquette","étiquette","maquette","allumette",
    "omelette","paillette","pipette","rondelle","mademoiselle","demoiselle","coccinelle","poubelle",
    "chapelle","vaisselle","dentelle","échelle","rebelle","cruelle","nouvelle","mensuel","annuel",
    "habituel","éventuel","spirituel","perpétuel","accueil","recueil","cercueil","orgueil","chevreuil",
    "fauteuil","feuillage","nouille","rouille","vadrouille","gargouille","embrouille","bouillon",
    "tourbillon","carillon","haillon","bâillon","pavillon","médaillon","échantillon","brouillon","grillon",
    "sillon","vermillon"
  ],
  "Collège": [
    "acquérir","apercevoir","atterrir","occurrence","dilemme","parallélépipède","hiéroglyphe","psychologie",
    "chrysalide","labyrinthe","rhinocéros","pharaon","archéologie","mythologie","hypocrite","sympathique",
    "antipathique","catastrophe","métaphore","apostrophe","éphémère","sphère","atmosphère","hémisphère",
    "cylindre","hexagone","symétrie","périmètre","équilatéral","isocèle","hypoténuse","coefficient",
    "pourcentage","proportionnalité","statistique","probabilité","algorithme","aquarium","gymnase",
    "athlète","olympique","championnat","adversaire","compétition","entraînement","endurance","résistance",
    "hyène","zoologie","botanique","chlorophylle","photosynthèse","asymétrique","antibiotique",
    "anesthésie","chirurgien","psychiatre","kinésithérapeute","orthophoniste","ophtalmologue","pédiatre",
    "diagnostic","symptôme","thérapie","hygiène","oxygène","hydrogène","azote","carbone","molécule",
    "atome","électron","neutron","proton","gravitation","accélération","trajectoire","galaxie","nébuleuse",
    "constellation","météorite","comète","astéroïde","éclipse","équinoxe","solstice","hémorragie",
    "asphyxie","rhumatisme","allergie","insomnie","amnésie","paranoïa","claustrophobie","arachnophobie",
    "xénophobie","monarchie","aristocratie","bourgeoisie","féodalité","seigneurie","croisade","cathédrale",
    "abbaye","monastère","enluminure","calligraphie","parchemin","imprimerie","renaissance","humanisme",
    "protestantisme","absolutisme","philosophe","encyclopédie","constitution","souveraineté","citoyenneté",
    "laïcité","fraternité","égalité","liberté"
  ],
  "Lycée": [
    "paradoxalement","épistémologie","herméneutique","métaphysique","phénoménologie","existentialisme",
    "dialectique","syllogisme","rhétorique","allitération","oxymore","euphémisme","hyperbole","litote",
    "périphrase","chiasme","anaphore","asyndète","synecdoque","métonymie","prosopopée","esthétique",
    "ontologie","transcendance","immanence","inconscient","catharsis","apothéose","hégémonie","oligarchie",
    "théocratie","totalitarisme","bureaucratie","jurisprudence","plébiscite","référendum","ecchymose",
    "schizophrénie","otorhinolaryngologiste","thermodynamique","électromagnétisme","stœchiométrie",
    "chromatographie","enzyme","mitochondrie","ribosome","chromosome","homéostasie","acquiescer",
    "obséquieux","pusillanime","vraisemblablement","inéluctablement","irrémédiablement","indubitablement",
    "ostensiblement","subrepticement","concomitamment","sciemment","prépondérance","quintessence",
    "réminiscence","obsolescence","effervescence","incandescence","luminescence","phosphorescence",
    "fluorescence","convalescence","adolescence","déliquescence","acquiescement","dysfonctionnement",
    "apprivoisement","anticonstitutionnellement","psychanalyse","aphorisme","apocryphe","anachronisme",
    "antithèse","antonyme","archétype","cacophonie","euphonie","polysémie","paronomase","tautologie",
    "pléonasme","sophisme","aporie","maïeutique","scepticisme","stoïcisme","épicurisme","hédonisme",
    "nihilisme","utilitarisme","empirisme","rationalisme","idéalisme","matérialisme","déterminisme",
    "phénomène","épiphénomène","corollaire","axiome","théorème","conjecture","asymptote","logarithme",
    "exponentielle","dérivée","primitive","intégrale","polynôme","discriminant","hyperbolique",
    "trigonométrie","stochastique","récurrence","équiprobable"
  ]
};
const NIVEAUX = Object.keys(MOTS);
